/* Synthesized, gesture-unlocked sound design and bounded Norwegian speech queue. */
class GameAudio {
 constructor(getState){this.getState=getState;this.context=null;this.master=null;this.engine=null;this.queue=[];this.current=null;this.generation=0;this.voices=[];this.synth=window.speechSynthesis;this.refreshVoices=()=>{this.voices=this.synth?.getVoices()||[];const label=document.getElementById('voice-note');if(label)label.textContent=this.voices.some(v=>/^(nb|no|nn)(-|_|$)/i.test(v.lang))?'Norsk opplesning er klar. Bokstavene leses når du trykker, og fakta leses ved ankomst.':'Bokstaver og fakta leses med norsk stemme når den finnes på enheten. Du kan legge til en norsk stemme i iPad-innstillingene. Spillet fungerer også uten lyd.';};this.refreshVoices();this.synth?.addEventListener('voiceschanged',this.refreshVoices);}
 unlock(){if(this.getState().muted)return;try{if(!this.context){this.context=new(window.AudioContext||window.webkitAudioContext)();this.master=this.context.createGain();this.master.gain.value=.65;this.master.connect(this.context.destination);}if(this.context.state==='suspended')this.context.resume().catch(()=>{});}catch{}}
 tone(freq=500,length=.12,shape='sine',volume=.065,delay=0,endFreq=freq){if(this.getState().muted||this.getState().paused)return;this.unlock();if(!this.context)return;const ctx=this.context,o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+delay;o.type=shape;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,endFreq),t+length);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+length);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+length+.03);o.onended=()=>{o.disconnect();g.disconnect();};}
 swoosh(duration=.5,strength=.06,up=true){if(this.getState().muted||this.getState().paused)return;this.unlock();if(!this.context)return;const ctx=this.context,t=ctx.currentTime,buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;filter.type='bandpass';filter.Q.value=.7;filter.frequency.setValueAtTime(up?180:1600,t);filter.frequency.exponentialRampToValueAtTime(up?2500:160,t+duration);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(strength,t+duration*.2);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);source.connect(filter);filter.connect(gain);gain.connect(this.master);source.start(t);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
 effect(name){switch(name){
 case 'letter':this.tone(600,.16,'sine',.045,0,900);break;
 case 'boost':this.swoosh(.38,.09);this.tone(150,.35,'triangle',.07,0,460);break;
 case 'super':this.swoosh(.85,.12);this.tone(140,.65,'triangle',.09,0,720);[659,830,988].forEach((f,i)=>this.tone(f,.28,'sine',.055,.08+i*.1));break;
 case 'wrong':this.tone(310,.20,'sine',.045,0,200);break;
 case 'launch':this.swoosh(1.3,.13);this.tone(70,1,'triangle',.085,0,230);break;
 case 'arrival':[523,659,784,1047].forEach((f,i)=>this.tone(f,.45,'sine',.06,i*.13));this.swoosh(.65,.04,false);break;
 case 'flyby':this.tone(440,.23,'sine',.05,0,660);this.tone(880,.35,'sine',.04,.16);this.swoosh(.7,.04);break;
 case 'sun':this.swoosh(1.2,.12,false);this.tone(95,.75,'triangle',.07,0,55);break;
 case 'rescue':[784,988,1175].forEach((f,i)=>this.tone(f,.3,'sine',.055,i*.12));break;
 case 'countdown':this.tone(420,.12,'sine',.065);break;
 }}
 makeEngine(){if(this.engine||!this.context)return;const ctx=this.context,o=ctx.createOscillator(),harmonic=ctx.createOscillator(),gain=ctx.createGain();o.type='sine';harmonic.type='triangle';o.frequency.value=65;harmonic.frequency.value=130;gain.gain.value=0;o.connect(gain);harmonic.connect(gain);gain.connect(this.master);o.start();harmonic.start();this.engine={o,harmonic,gain};}
 update(){if(!this.context)return;const s=this.getState(),active=s.mode==='flight'&&!s.muted&&!s.paused;this.master.gain.setTargetAtTime(s.muted||s.paused?0:this.current?.id?.startsWith('letter')?.36:(this.current?.id?.startsWith('fact')||this.current?.id?.startsWith('flyby'))?.20:.65,this.context.currentTime,.045);if(active)this.makeEngine();if(!this.engine)return;const t=this.context.currentTime;this.engine.gain.gain.setTargetAtTime(active?.012+Math.max(0,s.speed-1)*.014:0,t,.09);this.engine.o.frequency.setTargetAtTime(62+s.speed*18,t,.1);this.engine.harmonic.frequency.setTargetAtTime(125+s.speed*35,t,.1);}
 stopSpeech(){this.generation++;this.queue=[];this.current=null;this.synth?.cancel();}
 say(text,{force=false,queue=false,id='info'}={}){const s=this.getState();if(s.muted||(!s.voice&&!force)||!this.synth||typeof SpeechSynthesisUtterance==='undefined')return;if(!queue)this.stopSpeech();if(this.queue.length>=8)this.queue.shift();this.queue.push({text,id,force});this.pump();}
 letter(letter,completedWord=''){const names={A:'a',B:'be',C:'se',D:'de',E:'e',F:'eff',G:'ge',H:'hå',I:'i',J:'jådd',K:'kå',L:'ell',M:'emm',N:'enn',O:'o',P:'pe',Q:'ku',R:'ærr',S:'ess',T:'te',U:'u',V:'ve',W:'dobbelt ve',X:'eks',Y:'y',Z:'sett',Æ:'æ',Ø:'ø',Å:'å'};if(this.current&&!this.current.id.startsWith('letter')&&!this.current.id.startsWith('flyby')&&!this.current.id.startsWith('fact'))this.stopSpeech();this.say((names[letter]||letter)+(completedWord?'. '+completedWord.toLowerCase()+'! '+(['Bra, Sofia!','Kult, Sofia!','Supert, Sofia!'][Math.floor(Math.random()*3)]):''),{queue:true,id:'letter-'+letter});}
 pump(){if(this.current||!this.queue.length)return;const s=this.getState();if(s.muted||(!s.voice&&!this.queue[0].force)||s.paused)return;const item=this.queue.shift(),u=new SpeechSynthesisUtterance(item.text),gen=this.generation;this.refreshVoices();u.lang='nb-NO';u.rate=item.id.startsWith('letter')?.9:.83;u.pitch=1.04;const voice=this.voices.find(v=>/^(nb|no)(-|_|$)/i.test(v.lang))||this.voices.find(v=>/^nn/i.test(v.lang));if(voice)u.voice=voice;this.current={...item,utterance:u};const finish=()=>{if(gen!==this.generation)return;this.current=null;this.pump();};u.onend=finish;u.onerror=finish;this.synth.speak(u);}
}
