/* Tiny dependency-free WebGL renderer: true perspective, depth buffer and lit 3D meshes. */
const M={
 identity:()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),
 mul(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;},
 model(p,s,r=[0,0,0]){let a=this.identity();a[12]=p[0];a[13]=p[1];a[14]=p[2];for(let i=0;i<3;i++){let t=this.identity(),c=Math.cos(r[i]||0),v=Math.sin(r[i]||0);if(i===0){t[5]=c;t[6]=v;t[9]=-v;t[10]=c;}if(i===1){t[0]=c;t[2]=-v;t[8]=v;t[10]=c;}if(i===2){t[0]=c;t[1]=v;t[4]=-v;t[5]=c;}a=this.mul(a,t);}let t=this.identity();t[0]=s[0];t[5]=s[1];t[10]=s[2];return this.mul(a,t);},
 perspective(fov,aspect,near,far){let f=1/Math.tan(fov/2),m=new Float32Array(16);m[0]=f/aspect;m[5]=f;m[10]=(far+near)/(near-far);m[11]=-1;m[14]=2*far*near/(near-far);return m;},
 look(eye,at){let z=norm(sub(eye,at)),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
};
const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{let n=Math.hypot(...a)||1;return a.map(v=>v/n);};
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);}
class SpaceRenderer{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl',{alpha:false,antialias:true,powerPreference:'low-power'});if(!this.gl)return new SoftwareRenderer(canvas);const gl=this.gl;
 const shader=(type,src)=>{let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 const vs=shader(gl.VERTEX_SHADER,'attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uMVP;uniform mat4 uModel;uniform vec3 uInvScale;varying vec3 vNormal;varying vec3 vPosition;varying vec3 vLocal;void main(){vLocal=aPosition;gl_Position=uMVP*vec4(aPosition,1.0);vNormal=normalize(mat3(uModel)*(aNormal*uInvScale));vPosition=(uModel*vec4(aPosition,1.0)).xyz;}');
 const fs=shader(gl.FRAGMENT_SHADER,'precision mediump float;uniform vec3 uColor;uniform float uGlow;uniform float uStripe;uniform float uTime;uniform float uSurface;uniform sampler2D uTexture;varying vec3 vNormal;varying vec3 vPosition;varying vec3 vLocal;void main(){float light=.48+.52*max(0.0,dot(normalize(vNormal),normalize(vec3(-.6,1.0,.8))));float bands=1.0-uStripe*.16*(.5+.5*sin(vPosition.y*12.0+sin(vPosition.x*3.0)*.6));vec3 base=uColor;if(uSurface>0.5){vec3 n=normalize(vLocal);vec2 uv=vec2(fract(atan(n.z,n.x)/6.2831853+1.0),acos(clamp(n.y,-1.0,1.0))/3.14159265);base=texture2D(uTexture,uv).rgb;light=.24+.76*max(0.0,dot(normalize(vNormal),normalize(vec3(-.6,1.0,.8))));}gl_FragColor=vec4(base*mix(light,1.04,uGlow)*bands,1.0);}');
 this.program=gl.createProgram();gl.attachShader(this.program,vs);gl.attachShader(this.program,fs);gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));gl.useProgram(this.program);this.loc={};for(const key of ['uMVP','uModel','uInvScale','uColor','uGlow','uStripe','uTime','uSurface','uTexture'])this.loc[key]=gl.getUniformLocation(this.program,key);this.pos=gl.getAttribLocation(this.program,'aPosition');this.normal=gl.getAttribLocation(this.program,'aNormal');gl.enable(gl.DEPTH_TEST);this.meshes={};this.makeMeshes();}
 mesh(name,data){const gl=this.gl,b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);this.meshes[name]={b,n:data.length/6};}
 makeMeshes(){const tri=(out,a,b,c,smooth=false)=>{const n=norm(cross(sub(b,a),sub(c,a)));for(const p of [a,b,c])out.push(...p,...(smooth?norm(p):n));};
 let a=[];const v=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];for(const [i,j,k,l]of [[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]]){tri(a,v[i],v[j],v[k]);tri(a,v[i],v[k],v[l]);}this.mesh('box',a);
 a=[];const rows=this.software?8:20,cols=this.software?12:28;const point=(t,p)=>[Math.sin(t)*Math.cos(p),Math.cos(t),Math.sin(t)*Math.sin(p)];for(let i=0;i<rows;i++)for(let j=0;j<cols;j++){const p=point(i*Math.PI/rows,j*Math.PI*2/cols),q=point((i+1)*Math.PI/rows,j*Math.PI*2/cols),r=point((i+1)*Math.PI/rows,(j+1)*Math.PI*2/cols),s=point(i*Math.PI/rows,(j+1)*Math.PI*2/cols);tri(a,p,q,r,true);tri(a,p,r,s,true);}this.mesh('sphere',a);
 a=[];const gr=this.software?22:40,gc=this.software?36:64;for(let i=0;i<gr;i++)for(let j=0;j<gc;j++){const p=point(i*Math.PI/gr,j*Math.PI*2/gc),q=point((i+1)*Math.PI/gr,j*Math.PI*2/gc),r=point((i+1)*Math.PI/gr,(j+1)*Math.PI*2/gc),s=point(i*Math.PI/gr,(j+1)*Math.PI*2/gc);tri(a,p,q,r,true);tri(a,p,r,s,true);}this.mesh('globe',a);
 for(const type of ['cone','cylinder']){a=[];for(let i=0;i<24;i++){let t=i*Math.PI/12,u=(i+1)*Math.PI/12,p=[Math.cos(t),-1,Math.sin(t)],q=[Math.cos(u),-1,Math.sin(u)],r=type==='cone'?[0,1,0]:[q[0],1,q[2]],s=[p[0],1,p[2]];tri(a,p,r,q);if(type==='cylinder'){tri(a,p,s,r);tri(a,s,[0,1,0],r);}tri(a,p,q,[0,-1,0]);}this.mesh(type,a);}
 a=[];for(let i=0;i<96;i++){let t=i*Math.PI/48,u=(i+1)*Math.PI/48,p=[Math.cos(t),0,Math.sin(t)],q=[Math.cos(u),0,Math.sin(u)],r=q.map(v=>v*1.65),s=p.map(v=>v*1.65);tri(a,p,q,r);tri(a,p,r,s);}this.mesh('ring',a);
 a=[];for(let i=0;i<64;i++){const t=i*Math.PI/32,u=(i+1)*Math.PI/32,p=[Math.cos(t),0,Math.sin(t)],q=[Math.cos(u),0,Math.sin(u)];tri(a,p,q,q.map(v=>v*1.025));tri(a,p,q.map(v=>v*1.025),p.map(v=>v*1.025));}this.mesh('ringlet',a);
 }
 begin(eye,at,bg){const gl=this.gl,c=this.canvas,dpr=Math.min(window.devicePixelRatio||1,1.6),w=Math.round(c.clientWidth*dpr),h=Math.round(c.clientHeight*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h;}gl.viewport(0,0,w,h);gl.clearColor(...rgb(bg),1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.vp=M.mul(M.perspective(.68,w/Math.max(h,1),.1,180),M.look(eye,at));}
 draw(mesh,p,s,color,rotation=[0,0,0],glow=0,stripe=0,texture=null){const gl=this.gl,m=this.meshes[mesh],model=this.root?M.mul(this.root,M.model(p,s,rotation)):M.model(p,s,rotation);gl.uniform1f(this.loc.uSurface,texture?1:0);if(texture){this.surfaceCache??=new WeakMap();let tex=this.surfaceCache.get(texture);gl.activeTexture(gl.TEXTURE0);if(!tex){tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);this.surfaceCache.set(texture,tex);}else gl.bindTexture(gl.TEXTURE_2D,tex);gl.uniform1i(this.loc.uTexture,0);}gl.bindBuffer(gl.ARRAY_BUFFER,m.b);gl.enableVertexAttribArray(this.pos);gl.enableVertexAttribArray(this.normal);gl.vertexAttribPointer(this.pos,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(this.normal,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(this.loc.uMVP,false,M.mul(this.vp,model));gl.uniformMatrix4fv(this.loc.uModel,false,model);gl.uniform3fv(this.loc.uInvScale,s.map(v=>1/(v*v)));gl.uniform3fv(this.loc.uColor,rgb(color));gl.uniform1f(this.loc.uGlow,glow);gl.uniform1f(this.loc.uStripe,stripe);gl.drawArrays(gl.TRIANGLES,0,m.n);}
}

// A software 3D fallback also works on browsers where hardware WebGL is disabled.
class SoftwareRenderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});if(!this.ctx)throw Error('No rendering context');this.software=true;this.meshes={};SpaceRenderer.prototype.makeMeshes.call(this);this.light=norm([-.6,1,.8]);}
 mesh(name,data){this.meshes[name]=data;}
 begin(eye,at,bg){const c=this.canvas,dpr=Math.min(1,960/Math.max(1,c.clientWidth));const w=Math.round(c.clientWidth*dpr),h=Math.round(c.clientHeight*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h;}this.ctx.fillStyle=bg;this.ctx.fillRect(0,0,w,h);this.eye=eye;this.vp=M.mul(M.perspective(.68,w/Math.max(h,1),.1,180),M.look(eye,at));this.faces=[];}
 transform(m,p,w=1){return [m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12]*w,m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13]*w,m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]*w,m[3]*p[0]+m[7]*p[1]+m[11]*p[2]+m[15]*w];}
 project(p){const a=this.transform(this.vp,p);return [(a[0]/a[3]*.5+.5)*this.canvas.width,(-a[1]/a[3]*.5+.5)*this.canvas.height,a[3]];}
 draw(mesh,p,s,color,rotation=[0,0,0],glow=0,stripe=0,texture=null){const m=this.root?M.mul(this.root,M.model(p,s,rotation)):M.model(p,s,rotation),data=this.meshes[mesh],col=rgb(color);if(mesh==='sphere'&&Math.max(...s)<.13){const center=this.transform(m,[0,0,0]),screen=this.project(center);if(screen[2]>.1)this.faces.push({circle:screen,r:Math.max(.65,s[0]*this.canvas.height/screen[2]),z:screen[2],color});return;}
 for(let i=0;i<data.length;i+=18){const pts=[0,6,12].map(j=>this.transform(m,data.slice(i+j,i+j+3))),center=[0,1,2].map(j=>(pts[0][j]+pts[1][j]+pts[2][j])/3);const nLocal=[0,1,2].map(j=>(data[i+3+j]+data[i+9+j]+data[i+15+j])/3/(s[j]*s[j]));const n=norm(this.transform(m,nLocal,0).slice(0,3));if(mesh!=='ringlet'&&dot(n,sub(this.eye,center))<0)continue;const ps=pts.map(v=>this.project(v));if(ps.some(v=>v[2]<.1))continue;const bands=1-stripe*.16*(.5+.5*Math.sin(center[1]*12+Math.sin(center[0]*3)*.6));const light=((.48+.52*Math.max(0,dot(n,this.light)))*(1-glow)+1.12*glow)*bands;const fill='rgb('+col.map(v=>Math.min(255,Math.round(v*255*light))).join(',')+')';if(texture){this.surfaceCache??=new WeakMap();let tex=this.surfaceCache.get(texture);if(!tex){tex={data:texture.getContext('2d').getImageData(0,0,texture.width,texture.height).data,w:texture.width,h:texture.height};this.surfaceCache.set(texture,tex);}const uv=[0,6,12].map(j=>{const v=norm(data.slice(i+j,i+j+3));return [(Math.atan2(v[2],v[0])/(2*Math.PI)+1)%1,Math.acos(Math.max(-1,Math.min(1,v[1])))/Math.PI];});if(Math.max(...uv.map(v=>v[0]))-Math.min(...uv.map(v=>v[0]))>.5)for(const v of uv)if(v[0]<.5)v[0]+=1;const lights=[0,6,12].map(j=>{const n=norm(this.transform(m,data.slice(i+j+3,i+j+6).map((v,k)=>v/(s[k]*s[k])),0).slice(0,3));return glow?1.04:.24+.76*Math.max(0,dot(n,this.light));});this.faces.push({ps,uv,tex,lights,wrap:true,color:fill});}else this.faces.push({ps,z:(ps[0][2]+ps[1][2]+ps[2][2])/3,color:fill});}}
 end(){const w=this.canvas.width,h=this.canvas.height,ctx=this.ctx;let img=ctx.getImageData(0,0,w,h),pix=new Uint32Array(img.data.buffer),depth=new Float32Array(w*h);const pack=color=>{const c=color.startsWith('#')?rgb(color).map(v=>Math.round(v*255)):color.slice(4,-1).split(',').map(Number);return (255<<24)|(c[2]<<16)|(c[1]<<8)|c[0];};
 for(const face of this.faces){const color=pack(face.color);if(face.circle){const[x,y,z]=face.circle,r=face.r,iz=1/z;for(let yy=Math.max(0,Math.floor(y-r));yy<Math.min(h,y+r);yy++)for(let xx=Math.max(0,Math.floor(x-r));xx<Math.min(w,x+r);xx++){const id=yy*w+xx;if((xx-x)*(xx-x)+(yy-y)*(yy-y)<=r*r&&iz>depth[id]){depth[id]=iz;pix[id]=color;}}continue;}
 const[a,b,c]=face.ps,den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<.001)continue;const minX=Math.max(0,Math.floor(Math.min(a[0],b[0],c[0]))),maxX=Math.min(w-1,Math.ceil(Math.max(a[0],b[0],c[0]))),minY=Math.max(0,Math.floor(Math.min(a[1],b[1],c[1]))),maxY=Math.min(h-1,Math.ceil(Math.max(a[1],b[1],c[1])));const dax=(b[1]-c[1])/den,dbx=(c[1]-a[1])/den,day=(c[0]-b[0])/den,dby=(a[0]-c[0])/den;let rowA=((b[1]-c[1])*(minX+.5-c[0])+(c[0]-b[0])*(minY+.5-c[1]))/den,rowB=((c[1]-a[1])*(minX+.5-c[0])+(a[0]-c[0])*(minY+.5-c[1]))/den;
 for(let y=minY;y<=maxY;y++,rowA+=day,rowB+=dby){let wa=rowA,wb=rowB,id=y*w+minX;for(let x=minX;x<=maxX;x++,id++,wa+=dax,wb+=dbx){const wc=1-wa-wb;if(wa>=-.00001&&wb>=-.00001&&wc>=-.00001){const iz=wa/a[2]+wb/b[2]+wc/c[2];if(iz>depth[id]){if(face.tex){const u=(wa*face.uv[0][0]/a[2]+wb*face.uv[1][0]/b[2]+wc*face.uv[2][0]/c[2])/iz,v=(wa*face.uv[0][1]/a[2]+wb*face.uv[1][1]/b[2]+wc*face.uv[2][1]/c[2])/iz,tx=Math.max(0,Math.min(face.tex.w-1,Math.floor((face.wrap?((u%1)+1)%1:u)*face.tex.w))),ty=Math.max(0,Math.min(face.tex.h-1,Math.floor(v*face.tex.h))),ti=(ty*face.tex.w+tx)*4,t=face.tex.data,alpha=t[ti+3]/255;if(alpha<.03)continue;const lighting=face.lights?(wa*face.lights[0]/a[2]+wb*face.lights[1]/b[2]+wc*face.lights[2]/c[2])/iz:1;const old=pix[id],r=Math.round(t[ti]*lighting*alpha+(old&255)*(1-alpha)),g=Math.round(t[ti+1]*lighting*alpha+((old>>>8)&255)*(1-alpha)),bcol=Math.round(t[ti+2]*lighting*alpha+((old>>>16)&255)*(1-alpha));pix[id]=(255<<24)|(bcol<<16)|(g<<8)|r;}else pix[id]=color;depth[id]=iz;}}}}}ctx.putImageData(img,0,0);}
}
/* Transparent painted decals, depth-tested just like the rest of the rocket. */
SpaceRenderer.prototype.decal=function(texture,p,size,rotation=[0,0,0]){
 const gl=this.gl;if(!this.decalPipeline){const compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(shader));return shader;};const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,'attribute vec3 aPosition;attribute vec2 aUV;uniform mat4 uMVP;varying vec2 vUV;void main(){gl_Position=uMVP*vec4(aPosition,1.0);vUV=aUV;}'));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,'precision mediump float;varying vec2 vUV;uniform sampler2D uTexture;void main(){vec4 c=texture2D(uTexture,vUV);if(c.a<0.03)discard;gl_FragColor=c;}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-.5,-.5,0,0,0,.5,-.5,0,1,0,.5,.5,0,1,1,-.5,-.5,0,0,0,.5,.5,0,1,1,-.5,.5,0,0,1]),gl.STATIC_DRAW);this.decalPipeline={program,buffer,pos:gl.getAttribLocation(program,'aPosition'),uv:gl.getAttribLocation(program,'aUV'),mvp:gl.getUniformLocation(program,'uMVP'),sampler:gl.getUniformLocation(program,'uTexture'),textures:new WeakMap()};}
 const pipe=this.decalPipeline;let tex=pipe.textures.get(texture);gl.activeTexture(gl.TEXTURE0);if(!tex){tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);pipe.textures.set(texture,tex);}else gl.bindTexture(gl.TEXTURE_2D,tex);
 const local=M.model(p,[size[0],size[1],1],rotation),model=this.root?M.mul(this.root,local):local;gl.useProgram(pipe.program);gl.bindBuffer(gl.ARRAY_BUFFER,pipe.buffer);gl.enableVertexAttribArray(pipe.pos);gl.enableVertexAttribArray(pipe.uv);gl.vertexAttribPointer(pipe.pos,3,gl.FLOAT,false,20,0);gl.vertexAttribPointer(pipe.uv,2,gl.FLOAT,false,20,12);gl.uniformMatrix4fv(pipe.mvp,false,M.mul(this.vp,model));gl.uniform1i(pipe.sampler,0);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.TRIANGLES,0,6);gl.disable(gl.BLEND);gl.useProgram(this.program);
};
SoftwareRenderer.prototype.decal=function(texture,p,size,rotation=[0,0,0]){this.decalCache??=new WeakMap();let tex=this.decalCache.get(texture);if(!tex){tex={data:texture.getContext('2d').getImageData(0,0,texture.width,texture.height).data,w:texture.width,h:texture.height};this.decalCache.set(texture,tex);}const local=M.model(p,[size[0],size[1],1],rotation),m=this.root?M.mul(this.root,local):local;const pts=[[-.5,-.5,0],[.5,-.5,0],[.5,.5,0],[-.5,.5,0]].map(v=>this.project(this.transform(m,v)));if(pts.some(v=>v[2]<.1))return;for(const ids of [[0,1,2],[0,2,3]])this.faces.push({ps:ids.map(i=>pts[i]),uv:ids.map(i=>[[0,1],[1,1],[1,0],[0,0]][i]),tex,color:'#ffffff'});};
