'use strict';
const $=id=>document.getElementById(id),earth=BODIES.find(p=>p.id==='earth');
let renderer;try{renderer=new SpaceRenderer($('scene'));}catch(e){$('fallback').hidden=false;console.error(e);}
const state={mode:'home',origin:earth,location:earth,target:null,selected:BODIES[4],elapsed:0,total:0,speed:1,word:'',index:0,wordNumber:0,wordLocked:false,paused:false,launchTime:0,arrivalTime:0,sunTime:0,angle:0,dragging:false,muted:false,hints:true,voice:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,visited:new Set(['earth']),shipColor:SHIP_COLORS[0].id,moonMode:true,clock:0,boostHold:0,boostFlash:0,rocketOffset:0,starTravel:0,rescueSound:false,route:[],passedCount:0,flyby:null,flybyTime:0,flybyQueue:[],played:new Set(),quizStars:0,quizCorrect:0};
const PROGRESS_KEY='sofias-romreise-progress-v1';
try{const saved=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null');const known=new Set([...BODIES,...MOONS].map(p=>p.id));if(Array.isArray(saved?.visited))for(const id of saved.visited)if(known.has(id))state.visited.add(id);if(SHIP_COLORS.some(c=>c.id===saved?.shipColor))state.shipColor=saved.shipColor;if(saved?.moonMode===false)state.moonMode=false;if(Array.isArray(saved?.played))for(const id of saved.played)if(known.has(id))state.played.add(id);if(Number.isFinite(saved?.quizStars))state.quizStars=Math.max(0,Math.min(999,Math.floor(saved.quizStars)));if(Number.isFinite(saved?.quizCorrect))state.quizCorrect=Math.max(0,Math.floor(saved.quizCorrect));}catch{}
let rewards=earnedRewards(state.visited);
// Moon mode opens when every planet is visited; the toggle lets Sofia put the moons away again.
function moonModeOn(){return rewards.moonMode&&state.moonMode;}
function destinations(){return moonModeOn()?[...BODIES,...MOONS]:BODIES;}
function parentOf(p){return BODIES.find(b=>b.id===p.parent);}
function bodiesVisited(){return BODIES.filter(p=>state.visited.has(p.id)).length;}
function saveProgress(){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify({visited:[...state.visited],shipColor:state.shipColor,moonMode:state.moonMode,played:[...state.played],quizStars:state.quizStars,quizCorrect:state.quizCorrect}));}catch{}}
function paintGraffiti(){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=256;const ctx=canvas.getContext('2d');ctx.translate(252,130);ctx.rotate(-.065);ctx.transform(1,0,-.16,1,0,0);const colors=['#ff76ba','#ffde71','#79e4e2','#ba95ff','#ff9e6e'];for(let i=0;i<21;i++){ctx.fillStyle=colors[i%5];ctx.beginPath();ctx.arc(Math.sin(i*5.2)*216,Math.cos(i*3.1)*67,3+i%5,0,Math.PI*2);ctx.fill();}ctx.font='italic 900 106px "Arial Black",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';ctx.strokeStyle='#202642';ctx.lineWidth=22;ctx.strokeText('SOFIA',0,0);ctx.strokeStyle='#fff8e7';ctx.lineWidth=11;ctx.strokeText('SOFIA',0,0);const letters='SOFIA',widths=[...letters].map(l=>ctx.measureText(l).width),total=widths.reduce((a,b)=>a+b,0);let x=-total/2;ctx.textAlign='left';for(let i=0;i<letters.length;i++){ctx.fillStyle=colors[i];ctx.fillText(letters[i],x,0);x+=widths[i];}ctx.strokeStyle='#79e4e2';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-177,66);ctx.lineTo(183,51);ctx.stroke();return canvas;}
const sofiaGraffiti=paintGraffiti();
function rewardMessage(before,after){const messages=[];if(!before.graffiti&&after.graffiti)messages.push('Kult, Sofia! Du har besøkt to forskjellige planeter! Nå har raketten fått tøff graffiti med navnet ditt!');if(!before.paint&&after.paint)messages.push('Fantastisk, Sofia! Fire planetbesøk! Raketten din har fått en ny lilla og rosa farge!');if(!before.palette&&after.palette)messages.push('Seks planetbesøk, Sofia! Nå kan du velge rakettfarge selv. Fargeknappene står hjemme på jorda!');if(!before.rainbow&&after.rainbow)messages.push('Hurra, Sofia! Du har oppdaget alle reisemålene! Nå lager raketten din regnbuer!');if(!before.moonMode&&after.moonMode)messages.push('Helt utrolig, Sofia! Du har besøkt alle planetene! Nå er månemodus åpen: månene går i bane rundt planetene sine, og du kan reise til dem.');if(!before.gold&&after.gold)messages.push('Du har besøkt alle månene, Sofia! Raketten din er blitt av rent gull, med en ekte diamant på toppen og et spor av gullmynter etter seg!');return messages.join(' ');}
const gameAudio=new GameAudio(()=>state);
let toastTimer,lastFocus,lastFrame=performance.now(),dragX=0,wordDelay=0,lastTap=0,lastTapX=0,lastTapY=0;
const scene=$('scene');
// No input elements: this keyboard never opens the iOS system keyboard.
function group(p,s,r,fn){const prev=renderer.root;renderer.root=prev?M.mul(prev,M.model(p,s,r)):M.model(p,s,r);fn();renderer.root=prev;}
function d(mesh,p,s,c,r=[0,0,0],g=0,b=0){renderer.draw(mesh,p,s,c,r,g,b);}
function tone(...args){gameAudio.tone(...args);}
function melody(){gameAudio.effect('arrival');}
function speak(text,force=false){gameAudio.say(text,{force});}
function triggerBoost(full=false){state.boostHold=full?1.4:.55;state.boostFlash=full?1.7:.85;gameAudio.effect(full?'super':'boost');$('boost-callout').textContent=state.speed>=5?'✦ ZOOOOM!':full?'✦ SUPERBOOST!':'✦ BOKSTAVKRAFT!';}
function updateBoost(dt){state.boostHold=Math.max(0,state.boostHold-dt);state.boostFlash=Math.max(0,state.boostFlash-dt);state.speed=relaxSpeed(state.speed,dt,state.boostHold);const desired=Math.min(4.2,Math.max(0,state.speed-1)*1.85)+(state.boostFlash>0?.45:0);state.rocketOffset+=(desired-state.rocketOffset)*(1-Math.exp(-dt*(desired>state.rocketOffset?9:2.5)));$('boost-callout').hidden=state.boostFlash<=0;}
function notify(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;$('toast').classList.remove('show');void $('toast').offsetWidth;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').hidden=true,2600);}
function updatePassport(){$('passport').textContent=moonModeOn()?`✦ ${bodiesVisited()} / 10 · 🌙 ${rewards.moons} / ${MOONS.length}`:`✦ ${bodiesVisited()} / 10 oppdaget`;const items=[];if(rewards.graffiti)items.push('★ SOFIA-graffiti');if(rewards.paint)items.push('★ Stjernerakett');if(rewards.palette)items.push('🎨 Fargevalg');if(rewards.rainbow)items.push('🌈 Regnbuespor');if(rewards.moonMode)items.push('🌙 Månemodus');if(rewards.gold)items.push('💎 Gullrakett');$('rocket-rewards').textContent=items.join(' · ');$('rocket-rewards').hidden=!items.length;$('inside-rewards').textContent=items.join(' · ');$('inside-rewards').hidden=!items.length;$('inside-progress').textContent=insideProgress();$('rewards-info').textContent=`${rewards.planets} av 8 planetbesøk og ${rewards.moons} av ${MOONS.length} måner. Graffiti etter 2, nye farger etter 4, eget fargevalg etter 6, månemodus når alle 8 planetene er besøkt og gullrakett med diamant og myntspor når alle månene er oppdaget. Jorda teller som hjemme. Pluto teller som et planetbesøk i spillet, sola som et eget reisemål.`;renderColorPicker();renderMoonToggle();}
// The toggle only appears once moon mode is earned, and it saves with the rest of the progress.
function renderMoonToggle(){const btn=$('moon-toggle');btn.hidden=!rewards.moonMode;btn.textContent=state.moonMode?'🌙 Månemodus på':'🌙 Månemodus av';btn.classList.toggle('on',state.moonMode);btn.setAttribute('aria-pressed',String(state.moonMode));}
// The colour picker opens with the sixth planet visit and lives on the home console.
function renderColorPicker(){const box=$('color-choice'),swatches=$('color-swatches');box.hidden=!rewards.palette;if(!rewards.palette){swatches.replaceChildren();return;}const current=shipPaint(rewards,state.shipColor);swatches.replaceChildren();for(const c of shipColorsFor(rewards)){const btn=document.createElement('button');btn.className='swatch'+(c.id===current.id?' selected':'');btn.type='button';btn.style.background=`linear-gradient(145deg,${c.body} 52%,${c.accent} 52%)`;btn.setAttribute('aria-label',c.name);btn.setAttribute('aria-pressed',String(c.id===current.id));btn.title=c.name;btn.onclick=()=>{state.shipColor=c.id;saveProgress();renderColorPicker();tone(430,.06);speak(c.name);};swatches.append(btn);}}
function showConsole(which){for(const id of ['home','inside','quiz','flight','play','arrival'])$(id+'-console').hidden=id!==which;}
function title(label,name,sub,badge){$('scene-label').textContent=label;$('scene-title').textContent=name;$('scene-sub').textContent=sub;$('scene-badge').textContent=badge;}
function dialog(id,open){const el=$(id);if(open){lastFocus=document.activeElement;el.hidden=false;el.querySelector('button:not([disabled])')?.focus();}else{el.hidden=true;if(lastFocus?.isConnected)lastFocus.focus();}}
function updateSettings(){for(const [id,key]of [['hint-toggle','hints'],['voice-toggle','voice'],['motion-toggle','reduced']]){const b=$(id);b.textContent=state[key]?'På':'Av';b.classList.toggle('on',state[key]);b.setAttribute('aria-pressed',String(state[key]));}}
function home(withMessage=false,preserveSpeech=false){state.mode='home';resetFx();state.location=earth;state.target=null;clearFlyby();state.paused=false;state.speed=1;state.boostHold=0;state.boostFlash=0;state.rocketOffset=0;$('boost-callout').hidden=true;state.angle=0;state.wordLocked=false;wordDelay=0;showConsole('home');$('pause').hidden=true;$('world-hint').hidden=true;$('scene-caption').hidden=true;$('countdown').hidden=true;$('app').classList.remove('boosted');for(const id of ['pause-modal','map-modal','system-modal'])$(id).hidden=true;title('HER BEGYNNER EVENTYRET','Hjemme på jorda','Raketten er klar. Hvor skal vi reise?','⌂ Din egen lille rombase');scene.setAttribute('aria-label','Sofia ved det brune huset sitt i skogen. Dra for å se deg rundt.');if(!preserveSpeech)gameAudio.stopSpeech();if(withMessage){notify('Trygt hjemme, Sofia! En ny rakett står klar.');if(!preserveSpeech)speak('Trygt hjemme, Sofia! En ny rakett står klar.');}}
function insideProgress(){const n=bodiesVisited(),left=10-n;
 return (left?`Veggen viser ${n} av 10 oppdagede reisemål. ${left===1?'Ett reisemål':left+' reisemål'} igjen å finne!`:'Alle ti reisemålene henger på veggen. Hele solsystemet er oppdaget!')+(moonModeOn()?` Månene: ${rewards.moons} av ${MOONS.length}.`:'')+(state.quizStars?` Du har ${state.quizStars} ${state.quizStars===1?'lesestjerne':'lesestjerner'} fra Planetspillet.`:' Prøv Planetspillet og få lesestjerner på veggen!');}
function enterHouse(){if(!['home','quiz'].includes(state.mode))return;state.mode='inside';resetFx();state.angle=0;state.dragging=false;showConsole('inside');
 $('inside-progress').textContent=insideProgress();$('world-hint').hidden=false;$('scene-caption').hidden=true;
 title('INNE HOS SOFIA','Rommet til Sofia','Navnet ditt står på veggen, og planetene du har besøkt henger under.','🏠 Hjemme i huset');
 scene.setAttribute('aria-label','Inne i huset til Sofia. Navnet SOFIA står på veggen, med de besøkte planetene under. Dra for å se deg rundt.');
 tone(300,.1);speak(insideProgress());}
function drawThumbnail(c,p){PlanetArt.thumbnail(c,p,moonModeOn()&&!p.parent?moonsOf(p.id):[]);}
function renderMap(){const grid=$('planet-grid');grid.replaceChildren();$('map-note').textContent=moonModeOn()?'Månene går i bane rundt planeten sin. Merkur og Venus har ingen måner. Sola er en stjerne, Pluto er en dvergplanet. Størrelser og reisetider er tilpasset spillet.':'Sola er en stjerne. Pluto er en dvergplanet. Størrelser og reisetider er tilpasset spillet.';for(const p of destinations()){const btn=document.createElement('button');const seen=state.visited.has(p.id);btn.className='planet-card'+(p.parent?' moon-card':'')+(seen?' visited':'')+(state.selected.id===p.id?' selected':'')+(state.location.id===p.id?' current':'');btn.setAttribute('aria-label',`${p.name}. ${p.type}. ${seen?'Besøkt. ':''}${state.location.id===p.id?'Du er her':p.id==='earth'?'Hjem med én gang':formatTime(duration(state.location,p))+' ved vanlig fart'}`);btn.setAttribute('aria-pressed',String(state.selected.id===p.id));btn.dataset.planet=p.id;const c=document.createElement('canvas');c.setAttribute('aria-hidden','true');btn.append(c);drawThumbnail(c,p);const name=document.createElement('b');name.textContent=p.name;btn.append(name);const label=document.createElement('small');label.textContent=state.location.id===p.id?'Du er her':p.type;btn.append(label);if(seen){const s=document.createElement('span');s.className='stamp';s.textContent='✓';s.setAttribute('aria-hidden','true');btn.append(s);}btn.onclick=()=>{state.selected=p;selectPlanet();tone(390,.06);speak(p.name);};grid.append(btn);}selectPlanet();}
function selectPlanet(){for(const el of $('planet-grid').children){const selected=el.dataset.planet===state.selected.id;el.classList.toggle('selected',selected);el.setAttribute('aria-pressed',String(selected));}const p=state.selected,here=p.id===state.location.id;const sec=duration(state.location,p);$('selection-title').textContent=p.name+' · '+p.type;$('selection-info').textContent=here?'Her er du nå. Velg et nytt sted!':p.id==='earth'?'Hjem igjen med én gang · ingen reisetid':p.id==='sun'?`${formatTime(sec)} · Veldig varm! Raketten vil brenne opp.`:`${formatTime(sec)} fra ${state.location.name.toLowerCase()} · Bokstavkraft gjør turen raskere!`;const route=p.id==='earth'?[]:tripRoute(state.location,p);$('map-route-preview').textContent=route.length?'På veien passerer vi: '+route.map(s=>s.body.name).join(' → '):'';$('launch').disabled=here;$('launch').textContent=here?'Du er her':p.id==='earth'?'⌂ Rett hjem':`Reis til ${p.name}`;}
// A poster of the solar system in orbital order, painted with the same globes as the rest of the game.
const systemNoise=i=>{const x=Math.sin(i*12.9898+i*i*.017)*43758.5453;return x-Math.floor(x);};
function systemRadius(p){return Math.max(12,Math.round(11+(p.size-2)*26));}
function systemExtent(p,moons,scale=1){const wide=p.id==='saturn'?2.25:p.id==='uranus'?2.15:1.1,tall=p.id==='saturn'?1.35:p.id==='uranus'?2.2:1.1,r=Math.max(10,Math.round(systemRadius(p)*scale));
 return {r,hx:Math.ceil(Math.max(r*wide,moons.length?r*1.45+30*scale:0)),hy:Math.ceil(Math.max(r*tall,moons.length?r*.62+30*scale:0))};}
// Stars and a dotted orbit that curves up towards the edges and passes right through the planet.
function drawOrbit(canvas,{w,h,dpr,seed,skip,glow,orbit,px}){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);
 const cx=w*px,cy=h/2,depth=Math.min(30,h*.36),y0=cy-2*px*(1-px)*depth;
 for(let i=0;i<Math.round(w*h/2300);i++){const x=systemNoise(seed*97+i*3+1)*w,y=systemNoise(seed*131+i*3+2)*h,size=systemNoise(seed*57+i*3+3);
  if(Math.hypot(x-cx,y-cy)<skip+7)continue;
  ctx.fillStyle='#fdf3d2'+(size>.93?'cc':size>.6?'8c':'55');
  if(size>.93){ctx.save();ctx.translate(x,y);ctx.beginPath();for(let k=0;k<4;k++){const a=k*Math.PI/2;ctx.lineTo(Math.cos(a)*2.9,Math.sin(a)*2.9);ctx.lineTo(Math.cos(a+.785)*.9,Math.sin(a+.785)*.9);}ctx.fill();ctx.restore();}
  else{ctx.beginPath();ctx.arc(x,y,size>.6?1.1:.8,0,Math.PI*2);ctx.fill();}}
 if(!orbit)return;ctx.strokeStyle=glow?'#ffd88e':'#f2e0ad';ctx.globalAlpha=glow?.72:.5;ctx.lineWidth=1.8;ctx.lineCap='round';ctx.setLineDash([.6,7]);
 ctx.beginPath();ctx.moveTo(0,y0);ctx.quadraticCurveTo(w/2,y0+depth,w,y0);ctx.stroke();}
function renderSystemMap(){const map=$('system-map');map.replaceChildren();
 for(const p of BODIES){const seen=state.visited.has(p.id),row=document.createElement('button');
  row.className='system-row'+(p.id==='sun'?' system-sun':'')+(seen?' visited':'')+(state.location.id===p.id?' current':'');
  row.dataset.planet=p.id;row.setAttribute('aria-label',`${p.name}. ${p.type}.${seen?' Besøkt.':''}`);
  const back=document.createElement('canvas');back.className='orbit-line';back.setAttribute('aria-hidden','true');row.append(back);
  const body=document.createElement('canvas');body.className='system-body';body.setAttribute('aria-hidden','true');row.append(body);
  const label=document.createElement('span');label.className='system-label';const name=document.createElement('span');
  const b=document.createElement('b');b.textContent=p.name;const small=document.createElement('small');small.textContent=state.location.id===p.id?'Du er her':p.type;
  name.append(b,small);label.append(name);
  if(seen){const s=document.createElement('span');s.className='stamp';s.textContent='✓';s.setAttribute('aria-hidden','true');label.append(s);}
  row.append(label);row.onclick=()=>{tone(392,.06);speak(p.name);};map.append(row);}}
function paintSystemMap(){const map=$('system-map'),width=map.clientWidth;if(!width)return;
 const dpr=Math.min(2,devicePixelRatio||1),scale=Math.max(.6,Math.min(1,width/420)),px=width<380?.31:.38;
 for(const row of map.children){const p=BODIES.find(b=>b.id===row.dataset.planet),body=row.querySelector('.system-body'),back=row.querySelector('.orbit-line');
  const sun=p.id==='sun',moons=moonModeOn()&&!sun?moonsOf(p.id):[],ext=systemExtent(p,moons,scale);
  const r=sun?Math.round(Math.max(92,Math.min(168,width*.34))):ext.r;
  const bw=sun?width:ext.hx*2,bh=sun?Math.round(r*.85):ext.hy*2,rowH=sun?bh+56:Math.max(62,bh+16);
  row.style.height=rowH+'px';body.style.width=bw+'px';body.style.height=bh+'px';if(!sun)body.style.left=(px*100).toFixed(1)+'%';
  row.querySelector('.system-label').style.left=sun?'':Math.round(width*px+ext.hx+(scale<.85?10:14))+'px';
  PlanetArt.thumbnail(body,p,moons,{w:Math.round(bw*dpr),h:Math.round(bh*dpr),r:Math.round(r*dpr),cx:Math.round(bw*dpr/2),cy:Math.round(sun?-r*.15*dpr:bh*dpr/2)});
  drawOrbit(back,{w:width,h:rowH,dpr,seed:BODIES.indexOf(p),skip:sun?r*.94:ext.hx,glow:state.visited.has(p.id),orbit:!sun,px});}}
function openSystemMap(){if(!['home','arrival'].includes(state.mode))return;tone(330,.08);renderSystemMap();dialog('system-modal',true);paintSystemMap();speak('Sola og planetene i rekkefølge');}
function openMap(){if(!['home','arrival'].includes(state.mode))return;tone(350,.08);state.selected=state.location.id==='earth'?BODIES[4]:earth;renderMap();dialog('map-modal',true);speak('Hei, Sofia! Hvor vil du reise nå?');}
function startTrip(p){if(!['home','arrival'].includes(state.mode)||p.id===state.location.id)return false;if(p.id==='earth'){dialog('map-modal',false);dialog('system-modal',false);tone(430,.12);home(true);return true;}state.origin=state.location;state.target=p;state.elapsed=0;state.total=duration(state.origin,p);clearFlyby();state.route=tripRoute(state.origin,p);startFlightFx();state.passedCount=0;renderRoute();state.speed=1;state.boostHold=0;state.boostFlash=0;state.rocketOffset=0;state.starTravel=0;state.rescueSound=false;$('boost-callout').hidden=true;state.launchTime=0;state.wordNumber=0;state.mode='launch';state.paused=false;state.angle=0;state.wordLocked=false;wordDelay=0;dialog('map-modal',false);showConsole('flight');$('pause').hidden=false;$('world-hint').hidden=true;$('scene-caption').hidden=true;$('route-title').textContent=`På vei til ${p.name}`;$('origin-name').textContent=state.origin.name;$('target-name').textContent=p.name;title('KLAR FOR AVREISE',`Neste stopp: ${p.name}`,'Trykk på bokstaver og gi raketten fart!',p.id==='sun'?'☀ En veldig varm stjerne':p.type);$('countdown').hidden=false;$('countdown').classList.remove('go');$('countdown').textContent='3';newWord(true);updateFlight();tone(440,.15);speak(`Klar, Sofia? Vi reiser til ${p.name}!`);return true;}
function clearFlyby(){state.flyby=null;state.flybyTime=0;state.flybyQueue=[];$('flyby-card').hidden=true;}
function renderRoute(){const el=$('route-stops');el.replaceChildren();el.hidden=!state.route.length;$('route-preview').textContent=state.route.length?'Vi passerer '+state.route.map(s=>s.body.name).join(' → ')+'.':'';for(const[ i,entry]of state.route.entries()){const chip=document.createElement('span');chip.className='route-stop'+(i<state.passedCount?' passed':'')+(state.flyby?.body.id===entry.body.id?' passing':'');chip.textContent=(i<state.passedCount?'✓ ':'')+entry.body.name;chip.title=i<state.passedCount?'Passert '+entry.body.name:'På veien: '+entry.body.name;el.append(chip);}if(state.target){const end=document.createElement('span');end.className='route-stop destination';end.textContent='⚑ '+state.target.name;el.append(end);}}
function beginFlyby(entry){state.flyby=entry;state.flybyTime=0;const belt=entry.body.id==='belt',next=state.route[state.passedCount]?.body||state.target;$('flyby-card').querySelector('.flyby-kicker').textContent=belt?'HOLD DEG FAST!':'SE UT AV VINDUET!';$('flyby-name').textContent=belt?'Vi flyr gjennom asteroidebeltet!':'Vi passerer '+entry.body.name+'!';if(belt)startBelt();$('flyby-next').textContent=next.id===state.target.id?'Videre til '+state.target.name+'!':'Neste på veien: '+next.name+' · Mål: '+state.target.name;$('flyby-card').style.setProperty('--planet-color',entry.body.color);$('flyby-card').hidden=false;gameAudio.effect('flyby');gameAudio.say(belt?'Hold deg fast, Sofia! Vi flyr gjennom asteroidebeltet. Trykk på steinene!':'Se, Sofia! Vi passerer '+entry.body.name+'!',{id:'flyby-'+entry.body.id});renderRoute();}
function updateFlybys(dt){const progress=state.elapsed/state.total;while(state.passedCount<state.route.length&&progress>=state.route[state.passedCount].fraction){state.flybyQueue.push(state.route[state.passedCount++]);}if(state.flyby){state.flybyTime+=dt;if(state.flybyTime>=(state.flyby.body.id==='belt'?8:5)){state.flyby=null;$('flyby-card').hidden=true;renderRoute();}}if(!state.flyby&&state.flybyQueue.length)beginFlyby(state.flybyQueue.shift());}
function newWord(first=false){const pool=destinations();let p=first?state.target:pool[(state.wordNumber*3+Math.max(0,pool.indexOf(state.target)))%pool.length];if(!p)p=earth;state.word=p.word;state.index=0;state.wordLocked=false;state.wordNumber++;$('feedback').textContent='Hjelp raketten med bokstavkraft!';let letters=[...new Set(state.word)];const extras='AEIOUMNRSPLTV';for(const l of extras){if(letters.length>=10)break;if(!letters.includes(l))letters.push(l);}letters=letters.sort();$('keyboard').replaceChildren();for(const letter of letters){const b=document.createElement('button');b.className='letter-key';b.textContent=letter;b.setAttribute('aria-label','Bokstav '+letter);b.onclick=()=>inputLetter(letter,b);$('keyboard').append(b);}renderWord();}
function renderWord(){$('word').replaceChildren();for(let i=0;i<state.word.length;i++){const span=document.createElement('span');span.className='slot'+(i<state.index?' done':i===state.index?' current':'');span.textContent=state.word[i];$('word').append(span);}$('word').setAttribute('aria-label',`${state.word}. ${state.index} av ${state.word.length} bokstaver.`);for(const b of $('keyboard').children){b.classList.toggle('hint',state.hints&&b.textContent===state.word[state.index]);b.disabled=state.wordLocked;}}
function inputLetter(letter,button){if(!['flight','launch'].includes(state.mode)||state.paused||state.wordLocked)return;const correct=letter===state.word[state.index];state.speed=accelerate(state.speed,correct);if(correct){state.index++;const full=state.index===state.word.length;flyLetter(letter,button);gameAudio.letter(letter,full?state.word:'');triggerBoost(full);$('feedback').textContent=['Kult, Sofia! Mer rakettkraft!','Bra, Sofia! Raketten får mer fart!','Du fant riktig bokstav, Sofia!'][state.index%3];if(full){state.speed+=.65;state.wordLocked=true;wordDelay=1.2;$('feedback').textContent='Hele navnet! SUPERBOOST! ✦';notify('✦ Bra, Sofia! Superboost!');}}else{state.boostHold=0;state.boostFlash=0;gameAudio.effect('wrong');gameAudio.letter(letter);$('feedback').textContent=`Prøv ${state.word[state.index]}! Du klarer det.`;button?.classList.add('wrong');setTimeout(()=>button?.classList.remove('wrong'),280);}renderWord();updateFlight();}
function updateFlight(){const percent=Math.min(100,state.elapsed/state.total*100)||0;$('progress-fill').style.width=percent+'%';$('progress').setAttribute('aria-valuenow',String(Math.round(percent)));$('eta').textContent=formatTime(Math.max(0,state.total-state.elapsed)/state.speed)+' igjen';$('speed').textContent='⚡ '+state.speed.toFixed(1).replace('.',',')+' × fart';$('app').classList.toggle('boosted',state.speed>1.1);$('boost-callout').hidden=state.boostFlash<=0;$('world').style.setProperty('--boost-strength',String(Math.min(1,Math.max(0,state.speed-1)/2)));}
function arrive(){clearFlyby();const before=rewards;state.visited.add(state.target.id);rewards=earnedRewards(state.visited);if(!before.gold&&rewards.gold)state.shipColor='gold';saveProgress();const rewardText=rewardMessage(before,rewards);updatePassport();if(rewardText){notify(!before.gold&&rewards.gold?'💎 Gullrakett, Sofia!':!before.moonMode&&rewards.moonMode?'🌙 Månemodus er åpen!':!before.rainbow&&rewards.rainbow?'🌈 Hurra, Sofia! Regnbuespor!':!before.palette&&rewards.palette?'🎨 Velg rakettfarge, Sofia!':!before.paint&&rewards.paint?'★ Nye farger, Sofia!':'★ SOFIA-graffiti er låst opp!');}state.location=state.target;state.arrivalTime=0;state.angle=0;state.wordLocked=true;$('pause').hidden=true;$('boost-callout').hidden=true;state.boostFlash=0;state.boostHold=0;state.rocketOffset=0;$('app').classList.remove('boosted');if(state.target.id==='earth'){home();notify('Velkommen hjem, astronaut!');melody();gameAudio.say('Velkommen hjem, Sofia! '+earth.fact,{id:'fact-earth'});return;}if(state.target.id==='sun'){state.mode='sun';state.sunTime=0;showConsole('arrival');$('arrival-title').textContent='Oi! Sola er for varm!';$('arrival-reward').textContent=rewardText;$('arrival-reward').hidden=!rewardText;$('arrival-fact').textContent='Raketten brenner opp. Sofia er trygg i redningskapselen og flyr hjem igjen.';$('next-trip').hidden=true;$('go-home').hidden=true;$('scene-caption').hidden=false;$('scene-caption').textContent='Redningskapselen passer på Sofia ♥';title('FOR VARMT FOR EN RAKETT','Oi, sola!','En stjerne full av lys og varme.','☀ Sola er en stjerne');$('sun-flash').classList.add('active');gameAudio.say('Se, Sofia! '+state.target.fact+' Oi! Raketten brenner opp. Sofia er trygg i redningskapselen og reiser hjem. '+rewardText,{id:'fact-sun'});gameAudio.effect('sun');return;}
 showArrival(rewardText);melody();arrivalFx();const game=playFor(state.location);gameAudio.say('Bra, Sofia! Velkommen til '+state.target.name+'! '+state.target.fact+' '+rewardText+(game?' Vil du leke? Trykk på den rosa knappen!':''),{id:'fact-'+state.target.id});}
// The arrival screen: the fact, the way on, and the game waiting on this world.
function showArrival(rewardText=''){const p=state.location,game=playFor(p);state.mode='arrival';state.angle=0;showConsole('arrival');$('next-trip').hidden=false;$('go-home').hidden=false;$('arrival-title').textContent='Hei, '+p.name+'!';$('arrival-fact').textContent=p.fact;$('arrival-reward').textContent=rewardText;$('arrival-reward').hidden=!rewardText;$('play-here').hidden=!game;if(game)$('play-here').textContent=`${game.icon} Lek: ${game.title}`+(state.played.has(p.id)?' ⭐':'');$('world-hint').hidden=false;const orbit=['jupiter','saturn','uranus','neptune'].includes(p.id);title(p.parent?'DU HAR OPPDAGET EN NY MÅNE':'DU HAR OPPDAGET ET NYTT STED',p.name,'Se deg rundt, lille romforsker!',p.type);$('scene-caption').hidden=false;$('scene-caption').textContent=orbit?'Vi flyr rundt – her kan vi ikke lande!':p.parent?`Måne i bane rundt ${parentOf(p).name}`:p.id==='pluto'?'En liten isverden langt, langt borte':'Se! '+({mercury:'Massevis av kratere',venus:'Et tykt teppe av skyer',mars:'Rødt støv danser rundt oss'}[p.id]||'Så fint det er her');scene.setAttribute('aria-label',`Romraketten ved ${p.name}. ${p.fact}`);}
// Stor skjerm: spillet rydder bort sin egen overskrift selv, og ber i tillegg nettleseren om ekte
// fullskjerm der det er lov. Safari på iPad sier nei til det siste, men bildet blir stort uansett.
function fullscreenOn(){return !!(document.fullscreenElement||document.webkitFullscreenElement);}
function immersiveOn(){return $('app').classList.contains('immersive');}
function setImmersive(on){const btn=$('fullscreen'),label=on?'Avslutt full skjerm':'Full skjerm';
 $('app').classList.toggle('immersive',on);btn.setAttribute('aria-pressed',String(on));btn.setAttribute('aria-label',label);btn.title=label;}
function toggleFullscreen(){const el=$('app'),on=!immersiveOn();setImmersive(on);tone(on?520:320,.07);
 if(on)notify('Stor skjerm! Trykk på knappen øverst til høyre for å gå tilbake.');
 try{if(on){const request=el.requestFullscreen||el.webkitRequestFullscreen;if(request)Promise.resolve(request.call(el)).catch(()=>{});}
  else if(fullscreenOn()){const exit=document.exitFullscreen||document.webkitExitFullscreen||document.webkitCancelFullScreen;if(exit)Promise.resolve(exit.call(document)).catch(()=>{});}}catch{}}
function setPause(value){if(!['flight','launch','sun'].includes(state.mode))return;state.paused=value;dialog('pause-modal',value);if(value)gameAudio.stopSpeech();gameAudio.update();}
$('open-map').onclick=openMap;$('next-trip').onclick=openMap;$('close-map').onclick=()=>dialog('map-modal',false);$('open-system').onclick=openSystemMap;$('enter-house').onclick=enterHouse;$('go-outside').onclick=()=>{tone(300,.08);home();};$('close-system').onclick=()=>dialog('system-modal',false);$('system-go').onclick=()=>{dialog('system-modal',false);openMap();};addEventListener('resize',()=>{if(!$('system-modal').hidden)paintSystemMap();});$('launch').onclick=()=>startTrip(state.selected);$('go-home').onclick=()=>startTrip(earth);$('sound').onclick=()=>{state.muted=!state.muted;$('sound').textContent=state.muted?'🔇':'🔊';$('sound').setAttribute('aria-label',state.muted?'Slå på lyd':'Slå av lyd');if(state.muted)gameAudio.stopSpeech();else tone(520,.13);gameAudio.update();};$('moon-toggle').onclick=()=>{state.moonMode=!state.moonMode;saveProgress();updatePassport();tone(state.moonMode?520:360,.1);notify(state.moonMode?'🌙 Månemodus på – månene er med!':'🌙 Månemodus av');speak(state.moonMode?'Månemodus på, Sofia! Nå kan du reise til månene også.':'Månemodus av.');};$('pause').onclick=()=>setPause(true);$('resume').onclick=()=>setPause(false);$('cancel-trip').onclick=()=>home();$('read-fact').onclick=()=>speak(state.location.fact,true);$('speak-word').onclick=()=>speak(state.word.toLowerCase(),true);
let pausedBeforeSettings=false;$('fullscreen').onclick=toggleFullscreen;
for(const ev of ['fullscreenchange','webkitfullscreenchange'])document.addEventListener(ev,()=>{if(!fullscreenOn()&&immersiveOn())setImmersive(false);});
$('settings').onclick=()=>{pausedBeforeSettings=state.paused;state.paused=true;updateSettings();dialog('settings-modal',true);gameAudio.stopSpeech();};$('close-settings').onclick=()=>{dialog('settings-modal',false);state.paused=pausedBeforeSettings;gameAudio.update();};for(const[id,key]of [['hint-toggle','hints'],['voice-toggle','voice'],['motion-toggle','reduced']])$(id).onclick=()=>{state[key]=!state[key];updateSettings();if(key==='hints')renderWord();if(key==='voice'&&!state.voice)gameAudio.stopSpeech();};
scene.addEventListener('pointerdown',e=>{const now=performance.now(),box=scene.getBoundingClientRect();
 if(tapScene(e.clientX-box.left,e.clientY-box.top)){lastTap=0;return;}
 if(now-lastTap<430&&Math.hypot(e.clientX-lastTapX,e.clientY-lastTapY)<40&&allowDoubleTap()){lastTap=0;toggleFullscreen();}
 else{lastTap=now;lastTapX=e.clientX;lastTapY=e.clientY;}
 if(['home','inside','arrival'].includes(state.mode)){state.dragging=true;dragX=e.clientX;scene.setPointerCapture(e.pointerId);}});scene.addEventListener('pointermove',e=>{if(!state.dragging)return;state.angle-=(e.clientX-dragX)*.007;if(state.mode==='inside')state.angle=Math.max(-.5,Math.min(.5,state.angle));dragX=e.clientX;});for(const event of ['pointerup','pointercancel','lostpointercapture'])scene.addEventListener(event,()=>state.dragging=false);
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(['launch','flight','sun'].includes(state.mode)&&$('settings-modal').hidden)setPause(true);gameAudio.stopSpeech();}lastFrame=performance.now();});
document.addEventListener('keydown',e=>{if(keyScene(e))return;const modal=[...document.querySelectorAll('.modal-shade')].find(el=>!el.hidden);if(modal){if(e.key==='Tab'){const buttons=[...modal.querySelectorAll('button:not([disabled]),a[href]')],first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}if(e.key==='Escape'){if(modal.id==='map-modal')dialog('map-modal',false);else if(modal.id==='system-modal')dialog('system-modal',false);else if(modal.id==='settings-modal')$('close-settings').click();else setPause(false);}return;}if(/^[a-zæøå]$/i.test(e.key)){inputLetter(e.key.toUpperCase());}else if(e.key==='Escape')setPause(true);});
scene.addEventListener('webglcontextlost',e=>{e.preventDefault();state.paused=true;gameAudio.stopSpeech();gameAudio.update();$('fallback').hidden=false;});scene.addEventListener('webglcontextrestored',()=>location.reload());
// Deterministic small 3D world: no downloads, trackers, fonts or external assets.
const trees=Array.from({length:28},(_,i)=>{const a=i*2.39996,r=4.6+(i%5)*.45;return {x:Math.cos(a)*r,z:Math.sin(a)*r,s:.66+(i%4)*.14};}).filter(t=>!(t.z>2&&Math.abs(t.x)<4));
const stars=Array.from({length:95},(_,i)=>({x:Math.sin(i*73.7)*27,y:Math.cos(i*91.3)*16,z:-6-(i%12)*2.5,s:.018+(i%3)*.012}));
function character(t){d('box',[0,.52,0],[.22,.33,.16],'#efb749');d('sphere',[0,1.09,0],[.31,.32,.29],'#f6d1a8');d('sphere',[0,1.21,-.08],[.33,.25,.28],'#77523c');d('sphere',[.28,1.08,-.09],[.12,.18,.12],'#77523c');d('sphere',[-.28,1.08,-.09],[.12,.18,.12],'#77523c');d('sphere',[-.105,1.11,.267],[.035,.043,.018],'#1a2a3e');d('sphere',[.105,1.11,.267],[.035,.043,.018],'#1a2a3e');d('box',[0,1.01,.284],[.065,.018,.012],'#c5766c');for(const x of [-.115,.115]){d('box',[x,.13,0],[.09,.19,.105],'#34426d');d('sphere',[x,.015,.06],[.12,.07,.17],'#f6ede0');}d('box',[-.34,.59,0],[.09,.24,.09],'#efb749',[0,0,-.3]);d('sphere',[-.4,.36,0],[.10,.10,.10],'#f6d1a8');d('box',[.36,.8,0],[.08,.24,.09],'#efb749',[0,0,-.65+Math.sin(t*3)*.15]);d('sphere',[.5,.96,0],[.10,.10,.10],'#f6d1a8');}
function rocket(t,fire=false,burning=0,lying=false,pilot=true){const paint=shipPaint(rewards,state.shipColor),white=burning?'#796960':paint.body,orange=burning?'#51444b':paint.accent;d('cylinder',[0,.9,0],[.48,1.08,.48],white);d('cone',[0,2.3,0],[.48,.48,.48],orange);d('cylinder',[0,.05,0],[.5,.16,.5],'#526d80');d('cylinder',[0,-.26,0],[.26,.18,.26],'#2a3a56');d('sphere',[0,1.62,.44],[.3,.3,.08],'#d6aa58');d('sphere',[0,1.62,.50],[.225,.225,.08],'#3b718d');d('sphere',[-.06,1.70,.568],[.062,.084,.02],'#b8eeec',[],.3);if(pilot&&state.mode!=='home'&&(state.mode!=='launch'||state.launchTime>=2)){d('sphere',[0,1.59,.575],[.13,.14,.025],'#f4cfa7');d('sphere',[-.045,1.62,.599],[.017,.021,.008],'#22304b');d('sphere',[.045,1.62,.599],[.017,.021,.008],'#22304b');}if(rewards.graffiti&&!burning)renderer.decal(sofiaGraffiti,lying?[0,.64,.505]:[0,.95,.507],lying?[1.5,.8]:[.92,.49],lying?[0,0,Math.PI/2]:[0,0,0]);if(rewards.gold&&!burning)d('gem',[0,2.93,0],[.28,.38,.28],'#cdf5ff',[0,state.reduced?.6:t*1.5,0],.55);for(const x of [-1,1])d('box',[x*.48,.09,0],[.16,.55,.22],orange,[0,0,-x*.27]);d('box',[0,.1,-.45],[.19,.5,.13],orange);if(fire){if(rewards.rainbow&&!burning){const colors=['#ff6389','#ffa35c','#ffe36b','#80e18b','#64dce9','#7e9aff','#c28eff'];for(let i=0;i<7;i++)for(let k=0;k<7;k++){const wave=state.reduced?0:Math.sin(t*5-k*.6)*.06;d('box',[(i-3)*.09+wave,-.85-k*.42,.05],[.049,.23,.06],colors[i],[],1);}}if(rewards.gold&&!burning){const cash=['#ffd94f','#7fd48d','#ffe27a'];for(let i=0;i<14;i++){const k=((state.reduced?.4:t*.45)+i*.0715)%1,y=-.8-k*3.3,side=i%2?1:-1,sway=side*(.22+k*.85)+Math.sin(i*2.3+t*2.1)*.12,spin=state.reduced?.6:t*3.2+i;if(i%3)d('cylinder',[sway,y,.14],[.15,.022,.15],cash[i%3],[Math.PI/2,spin,.45*side],.45);else d('box',[sway,y,.14],[.17,.014,.1],cash[i%3],[spin*.5,spin,.3*side],.3);}}const n=state.reduced?1:1+.12*Math.sin(t*35);const boost=Math.min(2.4,Math.max(0,state.speed-1));const f=(.75+Math.min(3,state.speed)*.35+boost*.7)*n;d('cone',[0,-.62-f*.35,0],[.24+boost*.055,f*.6,.24+boost*.055],boost>.3?'#69dfe9':'#ff9747',[Math.PI,0,0],1);d('cone',[0,-.58-f*.23,.01],[.16+boost*.02,f*.4,.16+boost*.02],boost>.3?'#d4ffff':'#ffdc75',[Math.PI,0,0],1);}}
function homeScene(t,launch=0){const a=state.angle,aspect=scene.clientWidth/Math.max(1,scene.clientHeight),dist=aspect<.85?23:aspect<1.3?20:18,ignite=state.mode==='launch'?Math.max(0,state.launchTime-2.2):0,shake=state.reduced?0:Math.min(1,ignite*2)*.09,rise=Math.min(launch,9)*.5;renderer.begin([Math.sin(a)*dist+Math.cos(a)*8+Math.sin(t*41)*shake,10+Math.cos(t*33)*shake,Math.cos(a)*dist-Math.sin(a)*8],[rise*.25,.5+rise,0],'#7faeb3');d('sphere',[0,-1.4,0],[7.3,1.1,6.25],'#3e7470');d('cylinder',[0,-.47,0],[7.25,.22,6.2],'#74a77f');d('cylinder',[2.6,-.17,.2],[1.8,.07,1.8],'#b3bab1');d('ring',[2.6,-.08,.2],[.86,.86,.86],'#ecebc6');d('box',[.1,-.15,1.3],[2.8,.035,.52],'#c0af87',[0,.18,0]);
 group([-2.25,0,-.45],[1,1,1],[0,.18,0],()=>{d('box',[0,.93,0],[1.3,1.1,1.04],'#946647');for(let i=0;i<7;i++)d('box',[0,.11+i*.29,1.05],[1.3,.014,.012],'#775139');d('box',[-.77,2.21,0],[.97,.10,1.35],'#5a3b34',[0,0,.57]);d('box',[.77,2.21,0],[.97,.10,1.35],'#5a3b34',[0,0,-.57]);d('box',[0,1.85,0],[.75,.3,1.03],'#8b5c3e');d('box',[.73,2.62,-.45],[.19,.58,.2],'#c19170');d('box',[.43,.53,1.06],[.32,.7,.055],'#493831');d('sphere',[.61,.54,1.14],[.044,.044,.02],'#f4ce6f');d('box',[-.64,1.04,1.07],[.36,.36,.035],'#ead9b8');d('box',[-.64,1.04,1.11],[.28,.28,.025],'#ffdf8d',[],.8);d('box',[-.64,1.04,1.14],[.025,.29,.025],'#b17c54');d('box',[-.64,1.04,1.14],[.29,.025,.025],'#b17c54');d('box',[.4,-.03,1.42],[.51,.12,.32],'#c6b796');});
 for(const tree of trees){group([tree.x,-.19,tree.z],[tree.s,tree.s,tree.s],[0,0,0],()=>{d('cylinder',[0,.5,0],[.13,.65,.13],'#765d46');d('cone',[0,1.12,0],[.73,.9,.73],'#386b5e');d('cone',[0,1.8,0],[.57,.78,.57],'#448770');d('cone',[0,2.36,0],[.38,.64,.38],'#5a987e');});}
 for(let i=0;i<11;i++){const x=Math.sin(i*6.2)*5,z=2.8+Math.cos(i*4)*1.8;d('sphere',[x,-.1,z],[.22,.14,.17],'#b6c4ad');}for(let i=0;i<13;i++){const x=-4.4+i*.21,z=1.9+Math.sin(i)*.3;d('sphere',[x,.0,z],[.07,.09,.07],i%2?'#ffdf83':'#e9ad87');}
 if(state.mode==='home'||state.launchTime<2){const walking=state.mode==='launch',progress=walking?Math.min(1,state.launchTime/2):0,walk=progress*progress*(3-2*progress),steps=progress*Math.PI*10,envelope=Math.sin(progress*Math.PI),wobble=walking&&!state.reduced?Math.sin(steps)*.15*envelope:0,bob=walking&&!state.reduced?Math.abs(Math.sin(steps))*.09*envelope:0,boarding=Math.max(0,(progress-.82)/.18);group([-.05+walk*2.65,bob+boarding*.45+homeJump(),1.85*(1-walk)],[.87,.87,.87],[0,walking?1.98:.1,wobble],()=>character(walking?0:t));}const wiggle=state.reduced?0:Math.sin(t*30)*fx.wiggle*.08;group([2.6,.44+launch,0],[.8,.8,.8],[wiggle,0,wiggle],()=>rocket(t,ignite>0));fx.rocketWorld=[2.6,1.16+launch,0];if(ignite>0)for(let i=0;i<18;i++){const a=i*2.4,r=Math.min(3.4,ignite*.55+i*.08),grow=.24+Math.min(.5,ignite*.12)+(i%4)*.05;d('sphere',[2.6+Math.cos(a)*r,.05+(i%3)*.16+Math.min(.9,ignite*.1)*(i%2),Math.sin(a)*r],[grow,grow*.72,grow],i%3?'#e3ebe0':'#cad6c8');}
 // Soft, floating clouds on the horizon.
 for(const [x,y,z]of [[-9,7,-16],[7,8,-17],[1,9,-23]]){d('sphere',[x,y,z],[1.9,.5,.7],'#c4ded6');d('sphere',[x-.4,y+.35,z],[.9,.65,.7],'#d4e6df');}}
// Sofia's own room: her name on the wall and a display case with every world she has visited.
function insideScene(t){const a=Math.max(-.5,Math.min(.5,state.angle)),aspect=scene.clientWidth/Math.max(1,scene.clientHeight),dist=aspect<.85?12.6:aspect<1.35?10.8:aspect<2.4?9.4:7.6;
 renderer.begin([Math.sin(a)*dist,2.35,Math.cos(a)*dist],[0,1.5,-.9],'#241a18');room(t);
 group([1.7,0,2.05],[.95,.95,.95],[0,-.34+(state.reduced?0:Math.sin(t*.6)*.1),0],()=>character(t));}
function room(t){
 d('box',[0,-.14,1.1],[4.4,.14,4.5],'#a9784d');for(let i=0;i<9;i++)d('box',[-3.9+i*.98,.012,1.1],[.022,.006,4.5],'#8a5c38');
 d('box',[0,1.82,-3.42],[4.4,1.96,.14],'#f0ddbc');d('box',[-4.42,1.82,-.75],[.14,1.96,2.65],'#e0cbaa');d('box',[4.42,1.82,-.75],[.14,1.96,2.65],'#e0cbaa');
 d('box',[0,.11,-3.26],[4.4,.11,.06],'#c9a882');d('box',[-4.26,.11,-.75],[.06,.11,2.65],'#c9a882');d('box',[4.26,.11,-.75],[.06,.11,2.65],'#c9a882');
 // A window with daylight and the forest outside, on the same wall as the desk.
 d('box',[-4.24,2.25,1.35],[.04,.72,.94],'#bfe4ef',[],.55);
 for(const [y,z,sy,sz]of [[2.99,1.35,.06,1],[1.51,1.35,.06,1],[2.25,2.37,.8,.06],[2.25,.33,.8,.06]])d('box',[-4.19,y,z],[.03,sy,sz],'#8d6144');
 d('box',[-4.17,2.25,1.35],[.02,.035,.94],'#a97c56');d('box',[-4.17,2.25,1.35],[.02,.72,.035],'#a97c56');
 d('cylinder',[-.5,.03,1.45],[1.6,.03,1.15],'#cf93a8');d('cylinder',[-.5,.045,1.45],[1.15,.03,.82],'#e4b3c1');
 // Sofia's bed along the right wall.
 d('box',[3.05,.34,-.5],[1.1,.34,1.8],'#b56a3c');d('box',[3.05,.74,-.5],[1.04,.13,1.74],'#f5efe2');
 d('box',[3.05,.84,.35],[1.05,.11,.95],'#79e4e2');d('sphere',[3.05,.92,-1.85],[.7,.2,.38],'#ffe6ef');
 // A desk with her model rocket and a lamp.
 d('box',[-3.45,1,1.25],[.78,.07,1.15],'#c99a62');for(const [x,z]of [[-4.1,.2],[-4.1,2.25],[-2.85,.2],[-2.85,2.25]])d('box',[x,.5,z],[.07,.5,.07],'#8d6144');
 group([-3.45,1.07,.45],[.3,.3,.3],[0,.9,0],()=>rocket(t,false,0,false,false));
 d('cylinder',[-3.45,1.17,2],[.09,.17,.09],'#7c8aa6');d('cone',[-3.45,1.52,2],[.32,.3,.32],'#ffd36b');d('sphere',[-3.45,1.38,2],[.13,.13,.13],'#fff3c4',[],1);
 // The name on the wall, painted with the same graffiti as the rocket.
 renderer.decal(sofiaGraffiti,[0,2.94,-3.27],[2.94,1.47]);
 // Every destination she has found, lit up in a case under her name; the rest wait as empty sockets.
 d('box',[0,1.48,-3.24],[3.25,.76,.07],'#7a5334');d('box',[0,1.48,-3.18],[3.1,.62,.03],'#241e3c');
 for(const [i,p]of BODIES.entries()){const x=-2.4+(i%5)*1.2,y=i<5?1.78:1.18,s=.15+(p.size-2)*.085,seen=state.visited.has(p.id);
  if(seen){renderer.draw('globe',[x,y,-3.05],[s,s,s],'#ffffff',[0,(state.reduced?0:t*.22)+i,0],p.id==='sun'?1:0,0,PlanetArt.get(p.id));
   for(const band of PlanetArt.rings(p.id))d('ringlet',[x,y,-3.05],[s*band.r,1,s*band.r],band.color,[0,0,p.id==='uranus'?1.35:.32],.35);
   d('ringlet',[x,y,-3.05],[s*1.75,1,s*1.75],'#ffb43d',[Math.PI/2,0,0],.45);
   if(state.played.has(p.id))d('star',[x+s*1.25,y+s*1.2,-3.02],[.075,.075,.075],'#ffcf4a',[0,0,.2],.55);}
  else{d('sphere',[x,y,-3.06],[s*.7,s*.7,s*.7],'#413c5c');d('ringlet',[x,y,-3.05],[s*1.75,1,s*1.75],'#6f6890',[Math.PI/2,0,0],.12);}}
 // Reading stars from the planet game, stuck on the wall above the bed.
 for(let i=0;i<Math.min(12,state.quizStars);i++)d('star',[4.25,3.05-Math.floor(i/4)*.62,-2.1+(i%4)*.78],[.27,.27,.27],'#ffcf4a',[0,-Math.PI/2,(i%3-1)*.2],.35+(state.reduced?0:.15*Math.sin(t*2+i)));}
function starScene(t,flight=false){for(const s of stars){let x=s.x;if(flight)x=((s.x-state.starTravel+60)%60+60)%60-30;d(flight&&!state.reduced?'box':'sphere',[x,s.y,s.z],flight&&!state.reduced?[s.s*(1+Math.min(7,state.speed)*5),s.s*.5,s.s*.5]:[s.s,s.s,s.s],s.s>.04?'#dce6f5':'#769aab',[],1);}}
function planet(p,t,pos=[0,0,0],scale=1,moons=true,rot=null,spin=t*.025){
 const tilt=p.id==='uranus'?1.7:p.id==='saturn'?.46:p.id==='earth'?.409:p.id==='mars'?.44:0;
 group(pos,[scale,scale,scale],rot||[.12,0,tilt],()=>{const sz=p.size;
 renderer.draw('globe',[0,0,0],[sz,sz*(p.id==='saturn'?.91:p.id==='jupiter'?.94:1),sz],'#ffffff',[0,spin,0],p.id==='sun'?1:0,0,PlanetArt.get(p.id));
 for(const band of PlanetArt.rings(p.id))d('ringlet',[0,0,0],[sz*band.r,1,sz*band.r],band.color,[],.35);
 if(moons&&moonModeOn()&&!p.parent)for(const m of moonsOf(p.id)){const a=(state.reduced?0:t*m.speed)+m.phase,r=sz*m.orbit;d('sphere',[Math.cos(a)*r,Math.sin(a*.7)*sz*.16,Math.sin(a)*r],[m.bead,m.bead,m.bead],m.color);}
 if(p.id==='sun'&&!state.reduced){for(let i=0;i<9;i++){const a=i*2.4+t*.018,rr=sz*1.025;d('sphere',[Math.cos(a)*rr,Math.sin(a)*rr,0],[.05,.13+.025*Math.sin(t+i),.04],'#ffd575',[0,0,a],1);}}
 });}
function flightScene(t){const pr=Math.min(1,state.elapsed/state.total),p=state.target,boost=Math.min(1.3,Math.max(0,state.speed-1)/2);
 // The last stretch swoops the planet in close, and a very fast rocket makes the whole view tremble.
 const near=Math.max(0,(pr-.84)/.16),approach=near*near*(3-2*near),shake=state.reduced?0:Math.min(.1,Math.max(0,state.speed-3)*.018),aspect=scene.clientWidth/Math.max(1,scene.clientHeight);
 renderer.begin([Math.sin(t*37)*shake,3+Math.cos(t*29)*shake,20],[0,.2,0],'#080f24');starScene(t,true);const targetX=Math.min(11,Math.max(5.5,7.9*aspect))-pr*1.8-approach*2.2,targetScale=.3+pr*.60+approach*.5;if(p.parent)planet(parentOf(p),t,[targetX+3.1,2.6,-15],targetScale*1.35);planet(p,t,[targetX,-.5,-5],targetScale);if(state.origin.id!=='sun'&&pr<.3)planet(state.origin,t,[-13-pr*25,-3,-9],.8);if(state.flyby&&state.flyby.body.id!=='belt'){const phase=Math.min(1,state.flybyTime/5),x=state.reduced?0:9-phase*22,scale=state.reduced?.48:.24+Math.sin(phase*Math.PI)*.45;planet(state.flyby.body,t,[x,-2.25,1],scale);}
 const bob=state.reduced?0:Math.sin(t*2)*.17;const surge=state.rocketOffset*(state.reduced?.4:1)*(1-pr*.45),requestedRocketX=-3+pr*.8+surge,safeGap=4.2+targetScale*1.8,rocketX=Math.min(requestedRocketX,targetX-safeGap);
 group([rocketX,bob,2],[1.4,1.4,1.4],[0,0,-Math.PI/2+.09-boost*.08],()=>rocket(t,true,0,true));fx.rocketWorld=[rocketX+1.26,bob,2];drawFlightFx(t,rocketX,bob,boost);
 if(boost>.04&&!state.reduced){for(let i=0;i<16;i++){const x=rocketX-2-((state.starTravel*1.8+i*.87)%12),y=bob+Math.sin(i*6.17)*(1.1+boost*2.4);d('box',[x,y,1-i%3],[.18+boost*.9,.012+boost*.006,.012],rewards.gold?(i%3?'#ffd94f':'#8fd99a'):(i%3?'#79e4e2':'#ffdf70'),[],1);}if(state.boostFlash>0){for(let i=0;i<2;i++){const age=(t*2+i*.5)%1,r=.45+age*1.2;d('ring',[rocketX-1.4-age*3,bob,2],[r,1,r],i?'#ffdf70':'#79e4e2',[0,0,Math.PI/2],.7);}}}}
function arrivalScene(t){const a=state.angle,p=state.location,dist=scene.clientWidth/Math.max(1,scene.clientHeight)<.95?20:17;renderer.begin([Math.sin(a)*dist,3,Math.cos(a)*dist],[0,0,0],'#090f27');starScene(t);if(p.parent)planet(parentOf(p),t,[-11,4.5,-21],1.25);planet(p,t);const rt=state.reduced?.3:t*.2,rx=Math.cos(rt)*5.7,rz=Math.sin(rt)*5.7;group([rx,.5,rz],[.52,.52,.52],[.1,0,-.24],()=>rocket(t,true));const effectColors={mercury:'#c9c2b7',venus:'#f0ce9e',mars:'#e5a176',jupiter:'#e9b381',saturn:'#e6d8b0',uranus:'#b9f4ee',neptune:'#7bbcec',pluto:'#d8efff'};const color=effectColors[p.id]||p.color;if(!state.reduced){for(let i=0;i<30;i++){const b=i*2.399+t*(p.id==='neptune'?.65:.13),r=p.size+.5+(i%5)*.32,y=Math.sin(i*2+t*.22)*p.size*.7;d(p.id==='pluto'?'box':'sphere',[Math.cos(b)*r,y,Math.sin(b)*r],[.025+(i%3)*.015,.03,.025],color,[t,i,t],.6);}}
 }
function sunScene(t){renderer.begin([0,3,19],[0,0,0],'#281329');starScene(t);planet(BODIES[0],t,[3,0,-2],1.3);const s=state.sunTime;if(s<2){group([-3+.5*s,0,2],[.8,.8,.8],[0,0,-1.2],()=>rocket(t,true,s>1));}if(s>.7){for(let i=0;i<24;i++){const a=i*2.4,age=Math.min(s-.7,2.5),r=age*(.5+i%5*.23);d('box',[-2.4+Math.cos(a)*r,Math.sin(a)*r,2+Math.sin(i)*r],[.05,.09,.05],i%2?'#ffba43':'#ff7540',[s*i,s,0],1);}}
 if(s>1.6){const x=-3-(s-1.6)*1.9,y=(s-1.6)*.55;d('sphere',[x,y,3],[.55,.49,.48],'#edeadc');d('sphere',[x,y,3.42],[.28,.27,.09],'#7fe0dd');d('sphere',[x,y-.01,3.51],[.15,.16,.035],'#f5cca7');d('cone',[x+.72,y,3],[.18,.5,.18],'#89dfda',[0,0,-Math.PI/2],1);}}
function tick(now){if(!renderer)return;const dt=Math.min((now-lastFrame)/1000,1);lastFrame=now;if(!state.paused){state.clock+=dt;if(state.mode==='launch'){const prev=Math.ceil(3-state.launchTime);state.launchTime+=dt;const n=Math.ceil(3-state.launchTime);if(n!==prev&&n>0)gameAudio.effect('countdown');if(state.launchTime>=2.6&&state.launchTime-dt<2.6)gameAudio.effect('launch');$('countdown').textContent=n>0?String(n):'AVGANG!';$('countdown').classList.toggle('go',n<=0);if(state.launchTime>=3.7){state.mode='flight';$('countdown').hidden=true;title('UTE PÅ ROMFERD',`Mot ${state.target.name}!`,'Bokstavkraft gir ekstra fart.',state.target.type);scene.setAttribute('aria-label',`Raketten flyr fra ${state.origin.name} til ${state.target.name}.`);}}
 if(state.mode==='flight'){state.elapsed+=dt*state.speed;updateBoost(dt);updateFlybys(dt);updateFlightFx(dt);state.starTravel+=dt*(2+state.speed*5);updateFlight();if(state.elapsed>=state.total)arrive();}if(wordDelay>0){wordDelay-=dt;if(wordDelay<=0&&['flight','launch'].includes(state.mode))newWord();}if(state.mode==='arrival')state.arrivalTime+=dt;if(state.mode==='play')updatePlay(dt);if(state.mode==='quiz')updateQuiz(dt);updateFx(dt);if(state.mode==='sun'){state.sunTime+=dt;if(state.sunTime>1.6&&!state.rescueSound){state.rescueSound=true;gameAudio.effect('rescue');}if(state.sunTime>7){$('sun-flash').classList.remove('active');home(true,true);}}}
 gameAudio.update();const t=state.clock;if(state.mode==='home')homeScene(t);else if(state.mode==='inside')insideScene(t);else if(state.mode==='launch'&&state.origin.id==='earth')homeScene(t,Math.pow(Math.max(0,state.launchTime-2.5),2)*6);else if(state.mode==='launch'||state.mode==='flight')flightScene(t);else if(state.mode==='arrival')arrivalScene(t);else if(state.mode==='play')playScene(t);else if(state.mode==='quiz')quizScene(t);else if(state.mode==='sun')sunScene(t);drawSparks();updateSpace();renderer.end?.();requestAnimationFrame(tick);}
// Optional browser agent integration uses the exact same actions as touch controls.
if(document.modelContext?.registerTool){for(const tool of [{name:'read_space_adventure',description:'Read current destination, journey progress and spelling prompt.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:state.mode,location:state.location.name,target:state.target?.name,word:state.word,nextLetter:state.word[state.index],speed:state.speed,progress:state.total?state.elapsed/state.total:0})},{name:'start_space_journey',description:'Start a new journey to a solar-system destination from home or after arrival. Moons are only available in moon mode.',inputSchema:{type:'object',properties:{destination:{type:'string',enum:[...BODIES,...MOONS].map(p=>p.id)}},required:['destination'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const p=destinations().find(p=>p.id===input.destination);if(!p||!startTrip(p))throw Error('Velg et annet reisemål når du er hjemme eller har kommet frem.');return {destination:p.name,seconds:p.id==='earth'?0:state.total};}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
updateSettings();updatePassport();
// The game loop starts at the end of house-quiz.js, the last script, once every scene and game exists.
