'use strict';
const $=id=>document.getElementById(id),earth=BODIES.find(p=>p.id==='earth');
let renderer;try{renderer=new SpaceRenderer($('scene'));}catch(e){$('fallback').hidden=false;console.error(e);}
const state={mode:'home',origin:earth,location:earth,target:null,selected:BODIES[4],elapsed:0,total:0,speed:1,word:'',index:0,wordNumber:0,wordLocked:false,paused:false,launchTime:0,arrivalTime:0,sunTime:0,angle:0,dragging:false,muted:false,hints:true,voice:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,visited:new Set(['earth']),clock:0,boostHold:0,boostFlash:0,rocketOffset:0,starTravel:0,rescueSound:false,route:[],passedCount:0,flyby:null,flybyTime:0,flybyQueue:[]};
const PROGRESS_KEY='sofias-romreise-progress-v1';
try{const saved=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null');if(Array.isArray(saved?.visited))for(const id of saved.visited)if(BODIES.some(p=>p.id===id))state.visited.add(id);}catch{}
let rewards=earnedRewards(state.visited);
function saveProgress(){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify({visited:[...state.visited]}));}catch{}}
function paintGraffiti(){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=192;const ctx=canvas.getContext('2d');ctx.translate(250,100);ctx.rotate(-.065);ctx.transform(1,0,-.16,1,0,0);const colors=['#ff76ba','#ffde71','#79e4e2','#ba95ff','#ff9e6e'];for(let i=0;i<21;i++){ctx.fillStyle=colors[i%5];ctx.beginPath();ctx.arc(Math.sin(i*5.2)*216,Math.cos(i*3.1)*67,3+i%5,0,Math.PI*2);ctx.fill();}ctx.font='italic 900 106px "Arial Black",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';ctx.strokeStyle='#202642';ctx.lineWidth=22;ctx.strokeText('SOFIA',0,0);ctx.strokeStyle='#fff8e7';ctx.lineWidth=11;ctx.strokeText('SOFIA',0,0);const letters='SOFIA',widths=[...letters].map(l=>ctx.measureText(l).width),total=widths.reduce((a,b)=>a+b,0);let x=-total/2;ctx.textAlign='left';for(let i=0;i<letters.length;i++){ctx.fillStyle=colors[i];ctx.fillText(letters[i],x,0);x+=widths[i];}ctx.strokeStyle='#79e4e2';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-177,66);ctx.lineTo(183,51);ctx.stroke();return canvas;}
const sofiaGraffiti=paintGraffiti();
function rewardMessage(before,after){const messages=[];if(!before.graffiti&&after.graffiti)messages.push('Kult, Sofia! Du har besøkt to forskjellige planeter! Nå har raketten fått tøff graffiti med navnet ditt!');if(!before.paint&&after.paint)messages.push('Fantastisk, Sofia! Fem planetbesøk! Raketten din har fått en ny lilla og rosa farge!');if(!before.rainbow&&after.rainbow)messages.push('Hurra, Sofia! Du har oppdaget alle reisemålene! Nå lager raketten din regnbuer!');return messages.join(' ');}
const gameAudio=new GameAudio(()=>state);
let toastTimer,lastFocus,lastFrame=performance.now(),dragX=0,wordDelay=0;
const scene=$('scene');
// No input elements: this keyboard never opens the iOS system keyboard.
function group(p,s,r,fn){const prev=renderer.root;renderer.root=prev?M.mul(prev,M.model(p,s,r)):M.model(p,s,r);fn();renderer.root=prev;}
function d(mesh,p,s,c,r=[0,0,0],g=0,b=0){renderer.draw(mesh,p,s,c,r,g,b);}
function tone(...args){gameAudio.tone(...args);}
function melody(){gameAudio.effect('arrival');}
function speak(text,force=false){gameAudio.say(text,{force});}
function triggerBoost(full=false){state.boostHold=full?1.4:.55;state.boostFlash=full?1.7:.85;gameAudio.effect(full?'super':'boost');$('boost-callout').textContent=full?'✦ SUPERBOOST!':'✦ BOKSTAVKRAFT!';}
function updateBoost(dt){state.boostHold=Math.max(0,state.boostHold-dt);state.boostFlash=Math.max(0,state.boostFlash-dt);state.speed=relaxSpeed(state.speed,dt,state.boostHold);const desired=Math.max(0,state.speed-1)*1.85+(state.boostFlash>0?.45:0);state.rocketOffset+=(desired-state.rocketOffset)*(1-Math.exp(-dt*(desired>state.rocketOffset?9:2.5)));$('boost-callout').hidden=state.boostFlash<=0;}
function notify(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;$('toast').classList.remove('show');void $('toast').offsetWidth;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').hidden=true,2600);}
function updatePassport(){$('passport').textContent=`✦ ${state.visited.size} / 10 oppdaget`;const items=[];if(rewards.graffiti)items.push('★ SOFIA-graffiti');if(rewards.paint)items.push('★ Stjernerakett');if(rewards.rainbow)items.push('🌈 Regnbuespor');$('rocket-rewards').textContent=items.join(' · ');$('rocket-rewards').hidden=!items.length;$('rewards-info').textContent=`${rewards.planets} av 8 planetbesøk. Graffiti etter 2, nye farger etter 5 og regnbuespor når alle 10 reisemål er oppdaget. Jorda teller som hjemme. Pluto teller som et planetbesøk i spillet, sola som et eget reisemål.`;}
function showConsole(which){for(const id of ['home','flight','arrival'])$(id+'-console').hidden=id!==which;}
function title(label,name,sub,badge){$('scene-label').textContent=label;$('scene-title').textContent=name;$('scene-sub').textContent=sub;$('scene-badge').textContent=badge;}
function dialog(id,open){const el=$(id);if(open){lastFocus=document.activeElement;el.hidden=false;el.querySelector('button:not([disabled])')?.focus();}else{el.hidden=true;if(lastFocus?.isConnected)lastFocus.focus();}}
function updateSettings(){for(const [id,key]of [['hint-toggle','hints'],['voice-toggle','voice'],['motion-toggle','reduced']]){const b=$(id);b.textContent=state[key]?'På':'Av';b.classList.toggle('on',state[key]);b.setAttribute('aria-pressed',String(state[key]));}}
function home(withMessage=false,preserveSpeech=false){state.mode='home';state.location=earth;state.target=null;clearFlyby();state.paused=false;state.speed=1;state.boostHold=0;state.boostFlash=0;state.rocketOffset=0;$('boost-callout').hidden=true;state.angle=0;state.wordLocked=false;wordDelay=0;showConsole('home');$('pause').hidden=true;$('world-hint').hidden=true;$('scene-caption').hidden=true;$('countdown').hidden=true;$('app').classList.remove('boosted');for(const id of ['pause-modal','map-modal'])$(id).hidden=true;title('HER BEGYNNER EVENTYRET','Hjemme på jorda','Raketten er klar. Hvor skal vi reise?','⌂ Din egen lille rombase');scene.setAttribute('aria-label','Sofia ved det brune huset sitt i skogen. Dra for å se deg rundt.');if(!preserveSpeech)gameAudio.stopSpeech();if(withMessage){notify('Trygt hjemme, Sofia! En ny rakett står klar.');if(!preserveSpeech)speak('Trygt hjemme, Sofia! En ny rakett står klar.');}}
function drawThumbnail(c,p){PlanetArt.thumbnail(c,p);}
function renderMap(){const grid=$('planet-grid');grid.replaceChildren();for(const p of BODIES){const btn=document.createElement('button');btn.className='planet-card'+(state.selected.id===p.id?' selected':'')+(state.location.id===p.id?' current':'');btn.setAttribute('aria-label',`${p.name}. ${p.type}. ${state.location.id===p.id?'Du er her':formatTime(duration(state.location,p))+' ved vanlig fart'}`);btn.setAttribute('aria-pressed',String(state.selected.id===p.id));btn.dataset.planet=p.id;const c=document.createElement('canvas');c.setAttribute('aria-hidden','true');btn.append(c);drawThumbnail(c,p);const name=document.createElement('b');name.textContent=p.name;btn.append(name);const label=document.createElement('small');label.textContent=state.location.id===p.id?'Du er her':p.type;btn.append(label);if(state.visited.has(p.id)){const s=document.createElement('span');s.className='stamp';s.textContent='✓';btn.append(s);}btn.onclick=()=>{state.selected=p;selectPlanet();tone(390,.06);speak(p.name);};grid.append(btn);}selectPlanet();}
function selectPlanet(){for(const el of $('planet-grid').children){const selected=el.dataset.planet===state.selected.id;el.classList.toggle('selected',selected);el.setAttribute('aria-pressed',String(selected));}const p=state.selected,here=p.id===state.location.id;const sec=duration(state.location,p);$('selection-title').textContent=p.name+' · '+p.type;$('selection-info').textContent=here?'Her er du nå. Velg et nytt sted!':p.id==='sun'?`${formatTime(sec)} · Veldig varm! Raketten vil brenne opp.`:`${formatTime(sec)} fra ${state.location.name.toLowerCase()} · Bokstavkraft gjør turen raskere!`;const route=buildRoute(state.location,p);$('map-route-preview').textContent=route.length?'På veien passerer vi: '+route.map(s=>s.body.name).join(' → '):'';$('launch').disabled=here;$('launch').textContent=here?'Du er her':`Reis til ${p.name}`;}
function openMap(){if(!['home','arrival'].includes(state.mode))return;tone(350,.08);state.selected=state.location.id==='earth'?BODIES[4]:earth;renderMap();dialog('map-modal',true);speak('Hei, Sofia! Hvor vil du reise nå?');}
function startTrip(p){if(!['home','arrival'].includes(state.mode)||p.id===state.location.id)return false;state.origin=state.location;state.target=p;state.elapsed=0;state.total=duration(state.origin,p);clearFlyby();state.route=buildRoute(state.origin,p);state.passedCount=0;renderRoute();state.speed=1;state.boostHold=0;state.boostFlash=0;state.rocketOffset=0;state.starTravel=0;state.rescueSound=false;$('boost-callout').hidden=true;state.launchTime=0;state.wordNumber=0;state.mode='launch';state.paused=false;state.angle=0;state.wordLocked=false;wordDelay=0;dialog('map-modal',false);showConsole('flight');$('pause').hidden=false;$('world-hint').hidden=true;$('scene-caption').hidden=true;$('route-title').textContent=`På vei til ${p.name}`;$('origin-name').textContent=state.origin.name;$('target-name').textContent=p.name;title('KLAR FOR AVREISE',`Neste stopp: ${p.name}`,'Trykk på bokstaver og gi raketten fart!',p.id==='sun'?'☀ En veldig varm stjerne':p.type);$('countdown').hidden=false;$('countdown').textContent='3';newWord(true);updateFlight();tone(440,.15);speak(`Klar, Sofia? Vi reiser til ${p.name}!`);return true;}
function clearFlyby(){state.flyby=null;state.flybyTime=0;state.flybyQueue=[];$('flyby-card').hidden=true;}
function renderRoute(){const el=$('route-stops');el.replaceChildren();el.hidden=!state.route.length;$('route-preview').textContent=state.route.length?'Vi passerer '+state.route.map(s=>s.body.name).join(' → ')+'.':'';for(const[ i,entry]of state.route.entries()){const chip=document.createElement('span');chip.className='route-stop'+(i<state.passedCount?' passed':'')+(state.flyby?.body.id===entry.body.id?' passing':'');chip.textContent=(i<state.passedCount?'✓ ':'')+entry.body.name;chip.title=i<state.passedCount?'Passert '+entry.body.name:'På veien: '+entry.body.name;el.append(chip);}if(state.target){const end=document.createElement('span');end.className='route-stop destination';end.textContent='⚑ '+state.target.name;el.append(end);}}
function beginFlyby(entry){state.flyby=entry;state.flybyTime=0;const next=state.route[state.passedCount]?.body||state.target;$('flyby-name').textContent='Vi passerer '+entry.body.name+'!';$('flyby-next').textContent=next.id===state.target.id?'Videre til '+state.target.name+'!':'Neste på veien: '+next.name+' · Mål: '+state.target.name;$('flyby-card').style.setProperty('--planet-color',entry.body.color);$('flyby-card').hidden=false;gameAudio.effect('flyby');gameAudio.say('Se, Sofia! Vi passerer '+entry.body.name+'!',{id:'flyby-'+entry.body.id});renderRoute();}
function updateFlybys(dt){const progress=state.elapsed/state.total;while(state.passedCount<state.route.length&&progress>=state.route[state.passedCount].fraction){state.flybyQueue.push(state.route[state.passedCount++]);}if(state.flyby){state.flybyTime+=dt;if(state.flybyTime>=5){state.flyby=null;$('flyby-card').hidden=true;renderRoute();}}if(!state.flyby&&state.flybyQueue.length)beginFlyby(state.flybyQueue.shift());}
function newWord(first=false){let p=first?state.target:BODIES[(state.wordNumber*3+BODIES.indexOf(state.target))%BODIES.length];if(!p)p=earth;state.word=p.word;state.index=0;state.wordLocked=false;state.wordNumber++;$('feedback').textContent='Hjelp raketten med bokstavkraft!';let letters=[...new Set(state.word)];const extras='AEIOUMNRSPLTV';for(const l of extras){if(letters.length>=10)break;if(!letters.includes(l))letters.push(l);}letters=letters.sort();$('keyboard').replaceChildren();for(const letter of letters){const b=document.createElement('button');b.className='letter-key';b.textContent=letter;b.setAttribute('aria-label','Bokstav '+letter);b.onclick=()=>inputLetter(letter,b);$('keyboard').append(b);}renderWord();}
function renderWord(){$('word').replaceChildren();for(let i=0;i<state.word.length;i++){const span=document.createElement('span');span.className='slot'+(i<state.index?' done':i===state.index?' current':'');span.textContent=state.word[i];$('word').append(span);}$('word').setAttribute('aria-label',`${state.word}. ${state.index} av ${state.word.length} bokstaver.`);for(const b of $('keyboard').children){b.classList.toggle('hint',state.hints&&b.textContent===state.word[state.index]);b.disabled=state.wordLocked;}}
function inputLetter(letter,button){if(!['flight','launch'].includes(state.mode)||state.paused||state.wordLocked)return;const correct=letter===state.word[state.index];state.speed=accelerate(state.speed,correct);if(correct){state.index++;const full=state.index===state.word.length;gameAudio.letter(letter,full?state.word:'');triggerBoost(full);$('feedback').textContent=['Kult, Sofia! Mer rakettkraft!','Bra, Sofia! Raketten får mer fart!','Du fant riktig bokstav, Sofia!'][state.index%3];if(full){state.speed=Math.min(3,state.speed+.65);state.wordLocked=true;wordDelay=1.2;$('feedback').textContent='Hele navnet! SUPERBOOST! ✦';notify('✦ Bra, Sofia! Superboost!');}}else{state.boostHold=0;state.boostFlash=0;gameAudio.effect('wrong');gameAudio.letter(letter);$('feedback').textContent=`Prøv ${state.word[state.index]}! Du klarer det.`;button?.classList.add('wrong');setTimeout(()=>button?.classList.remove('wrong'),280);}renderWord();updateFlight();}
function updateFlight(){const percent=Math.min(100,state.elapsed/state.total*100)||0;$('progress-fill').style.width=percent+'%';$('progress').setAttribute('aria-valuenow',String(Math.round(percent)));$('eta').textContent=formatTime(Math.max(0,state.total-state.elapsed)/state.speed)+' igjen';$('speed').textContent='⚡ '+state.speed.toFixed(1).replace('.',',')+' × fart';$('app').classList.toggle('boosted',state.speed>1.1);$('boost-callout').hidden=state.boostFlash<=0;$('world').style.setProperty('--boost-strength',String(Math.min(1,Math.max(0,state.speed-1)/2)));}
function arrive(){clearFlyby();const before=rewards;state.visited.add(state.target.id);rewards=earnedRewards(state.visited);saveProgress();const rewardText=rewardMessage(before,rewards);updatePassport();if(rewardText){notify(!before.rainbow&&rewards.rainbow?'🌈 Hurra, Sofia! Regnbuespor!':!before.paint&&rewards.paint?'★ Nye farger, Sofia!':'★ SOFIA-graffiti er låst opp!');}state.location=state.target;state.arrivalTime=0;state.angle=0;state.wordLocked=true;$('pause').hidden=true;$('boost-callout').hidden=true;state.boostFlash=0;state.boostHold=0;state.rocketOffset=0;$('app').classList.remove('boosted');if(state.target.id==='earth'){home();notify('Velkommen hjem, astronaut!');melody();gameAudio.say('Velkommen hjem, Sofia! '+earth.fact,{id:'fact-earth'});return;}if(state.target.id==='sun'){state.mode='sun';state.sunTime=0;showConsole('arrival');$('arrival-title').textContent='Oi! Sola er for varm!';$('arrival-reward').textContent=rewardText;$('arrival-reward').hidden=!rewardText;$('arrival-fact').textContent='Raketten brenner opp. Sofia er trygg i redningskapselen og flyr hjem igjen.';$('next-trip').hidden=true;$('go-home').hidden=true;$('scene-caption').hidden=false;$('scene-caption').textContent='Redningskapselen passer på Sofia ♥';title('FOR VARMT FOR EN RAKETT','Oi, sola!','En stjerne full av lys og varme.','☀ Sola er en stjerne');$('sun-flash').classList.add('active');gameAudio.say('Se, Sofia! '+state.target.fact+' Oi! Raketten brenner opp. Sofia er trygg i redningskapselen og reiser hjem. '+rewardText,{id:'fact-sun'});gameAudio.effect('sun');return;}
 state.mode='arrival';showConsole('arrival');$('next-trip').hidden=false;$('go-home').hidden=false;$('arrival-title').textContent='Hei, '+state.target.name+'!';$('arrival-fact').textContent=state.target.fact;$('arrival-reward').textContent=rewardText;$('arrival-reward').hidden=!rewardText;$('world-hint').hidden=false;const orbit=['jupiter','saturn','uranus','neptune'].includes(state.target.id);title('DU HAR OPPDAGET ET NYTT STED',state.target.name,'Se deg rundt, lille romforsker!',state.target.type);$('scene-caption').hidden=false;$('scene-caption').textContent=orbit?'Vi flyr rundt – her kan vi ikke lande!':state.target.id==='pluto'?'En liten isverden langt, langt borte':'Se! '+({mercury:'Massevis av kratere',venus:'Et tykt teppe av skyer',mars:'Rødt støv danser rundt oss'}[state.target.id]||'Så fint det er her');melody();gameAudio.say('Bra, Sofia! Velkommen til '+state.target.name+'! '+state.target.fact+' '+rewardText,{id:'fact-'+state.target.id});scene.setAttribute('aria-label',`Romraketten ved ${state.target.name}. ${state.target.fact}`);}
function setPause(value){if(!['flight','launch','sun'].includes(state.mode))return;state.paused=value;dialog('pause-modal',value);if(value)gameAudio.stopSpeech();gameAudio.update();}
$('open-map').onclick=openMap;$('next-trip').onclick=openMap;$('close-map').onclick=()=>dialog('map-modal',false);$('launch').onclick=()=>startTrip(state.selected);$('go-home').onclick=()=>startTrip(earth);$('sound').onclick=()=>{state.muted=!state.muted;$('sound').textContent=state.muted?'🔇':'🔊';$('sound').setAttribute('aria-label',state.muted?'Slå på lyd':'Slå av lyd');if(state.muted)gameAudio.stopSpeech();else tone(520,.13);gameAudio.update();};$('pause').onclick=()=>setPause(true);$('resume').onclick=()=>setPause(false);$('cancel-trip').onclick=()=>home();$('read-fact').onclick=()=>speak(state.location.fact,true);$('speak-word').onclick=()=>speak(state.word.toLowerCase(),true);
let pausedBeforeSettings=false;$('settings').onclick=()=>{pausedBeforeSettings=state.paused;state.paused=true;updateSettings();dialog('settings-modal',true);gameAudio.stopSpeech();};$('close-settings').onclick=()=>{dialog('settings-modal',false);state.paused=pausedBeforeSettings;gameAudio.update();};for(const[id,key]of [['hint-toggle','hints'],['voice-toggle','voice'],['motion-toggle','reduced']])$(id).onclick=()=>{state[key]=!state[key];updateSettings();if(key==='hints')renderWord();if(key==='voice'&&!state.voice)gameAudio.stopSpeech();};
scene.addEventListener('pointerdown',e=>{if(['home','arrival'].includes(state.mode)){state.dragging=true;dragX=e.clientX;scene.setPointerCapture(e.pointerId);}});scene.addEventListener('pointermove',e=>{if(!state.dragging)return;state.angle+=(e.clientX-dragX)*.007;dragX=e.clientX;});for(const event of ['pointerup','pointercancel','lostpointercapture'])scene.addEventListener(event,()=>state.dragging=false);
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(['launch','flight','sun'].includes(state.mode)&&$('settings-modal').hidden)setPause(true);gameAudio.stopSpeech();}lastFrame=performance.now();});
document.addEventListener('keydown',e=>{const modal=[...document.querySelectorAll('.modal-shade')].find(el=>!el.hidden);if(modal){if(e.key==='Tab'){const buttons=[...modal.querySelectorAll('button:not([disabled]),a[href]')],first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}if(e.key==='Escape'){if(modal.id==='map-modal')dialog('map-modal',false);else if(modal.id==='settings-modal')$('close-settings').click();else setPause(false);}return;}if(/^[a-zæøå]$/i.test(e.key)){inputLetter(e.key.toUpperCase());}else if(e.key==='Escape')setPause(true);});
scene.addEventListener('webglcontextlost',e=>{e.preventDefault();state.paused=true;gameAudio.stopSpeech();gameAudio.update();$('fallback').hidden=false;});scene.addEventListener('webglcontextrestored',()=>location.reload());
// Deterministic small 3D world: no downloads, trackers, fonts or external assets.
const trees=Array.from({length:28},(_,i)=>{const a=i*2.39996,r=4.6+(i%5)*.45;return {x:Math.cos(a)*r,z:Math.sin(a)*r,s:.66+(i%4)*.14};}).filter(t=>!(t.z>2&&Math.abs(t.x)<4));
const stars=Array.from({length:95},(_,i)=>({x:Math.sin(i*73.7)*27,y:Math.cos(i*91.3)*16,z:-6-(i%12)*2.5,s:.018+(i%3)*.012}));
function character(t){d('box',[0,.52,0],[.22,.33,.16],'#efb749');d('sphere',[0,1.09,0],[.31,.32,.29],'#f6d1a8');d('sphere',[0,1.21,-.08],[.33,.25,.28],'#77523c');d('sphere',[.28,1.08,-.09],[.12,.18,.12],'#77523c');d('sphere',[-.28,1.08,-.09],[.12,.18,.12],'#77523c');d('sphere',[-.105,1.11,.267],[.035,.043,.018],'#1a2a3e');d('sphere',[.105,1.11,.267],[.035,.043,.018],'#1a2a3e');d('box',[0,1.01,.284],[.065,.018,.012],'#c5766c');for(const x of [-.115,.115]){d('box',[x,.13,0],[.09,.19,.105],'#34426d');d('sphere',[x,.015,.06],[.12,.07,.17],'#f6ede0');}d('box',[-.34,.59,0],[.09,.24,.09],'#efb749',[0,0,-.3]);d('sphere',[-.4,.36,0],[.10,.10,.10],'#f6d1a8');d('box',[.36,.8,0],[.08,.24,.09],'#efb749',[0,0,-.65+Math.sin(t*3)*.15]);d('sphere',[.5,.96,0],[.10,.10,.10],'#f6d1a8');}
function rocket(t,fire=false,burning=0){const white=burning?'#796960':rewards.paint?'#ad83ff':'#f4f0e5',orange=burning?'#51444b':rewards.paint?'#ff78bd':'#e78457';d('cylinder',[0,.9,0],[.48,1.08,.48],white);d('cone',[0,2.3,0],[.48,.48,.48],orange);d('cylinder',[0,.05,0],[.5,.16,.5],'#526d80');d('cylinder',[0,-.26,0],[.26,.18,.26],'#2a3a56');d('sphere',[0,1.62,.44],[.3,.3,.08],'#d6aa58');d('sphere',[0,1.62,.50],[.225,.225,.08],'#3b718d');d('sphere',[-.06,1.70,.568],[.062,.084,.02],'#b8eeec',[],.3);if(state.mode!=='home'&&(state.mode!=='launch'||state.launchTime>=2)){d('sphere',[0,1.59,.575],[.13,.14,.025],'#f4cfa7');d('sphere',[-.045,1.62,.599],[.017,.021,.008],'#22304b');d('sphere',[.045,1.62,.599],[.017,.021,.008],'#22304b');}if(rewards.graffiti&&!burning)renderer.decal(sofiaGraffiti,[0,.64,.505],[1.28,.66],[0,0,Math.PI/2]);for(const x of [-1,1])d('box',[x*.48,.09,0],[.16,.55,.22],orange,[0,0,-x*.27]);d('box',[0,.1,-.45],[.19,.5,.13],orange);if(fire){if(rewards.rainbow&&!burning){const colors=['#ff6389','#ffa35c','#ffe36b','#80e18b','#64dce9','#7e9aff','#c28eff'];for(let i=0;i<7;i++)for(let k=0;k<7;k++){const wave=state.reduced?0:Math.sin(t*5-k*.6)*.06;d('box',[(i-3)*.09+wave,-.85-k*.42,.05],[.049,.23,.06],colors[i],[],1);}}const n=state.reduced?1:1+.12*Math.sin(t*35);const boost=Math.max(0,state.speed-1);const f=(.75+state.speed*.35+boost*.7)*n;d('cone',[0,-.62-f*.35,0],[.24+boost*.055,f*.6,.24+boost*.055],boost>.3?'#69dfe9':'#ff9747',[Math.PI,0,0],1);d('cone',[0,-.58-f*.23,.01],[.16+boost*.02,f*.4,.16+boost*.02],boost>.3?'#d4ffff':'#ffdc75',[Math.PI,0,0],1);}}
function homeScene(t,launch=0){const a=state.angle,aspect=scene.clientWidth/Math.max(1,scene.clientHeight),dist=aspect<.85?23:aspect<1.3?20:18;renderer.begin([Math.sin(a)*dist+Math.cos(a)*8,10,Math.cos(a)*dist-Math.sin(a)*8],[0,.5,0],'#7faeb3');d('sphere',[0,-1.4,0],[7.3,1.1,6.25],'#3e7470');d('cylinder',[0,-.47,0],[7.25,.22,6.2],'#74a77f');d('cylinder',[2.6,-.17,.2],[1.8,.07,1.8],'#b3bab1');d('ring',[2.6,-.08,.2],[.86,.86,.86],'#ecebc6');d('box',[.1,-.15,1.3],[2.8,.035,.52],'#c0af87',[0,.18,0]);
 group([-2.25,0,-.45],[1,1,1],[0,.18,0],()=>{d('box',[0,.93,0],[1.3,1.1,1.04],'#946647');for(let i=0;i<7;i++)d('box',[0,.11+i*.29,1.05],[1.3,.014,.012],'#775139');d('box',[-.77,2.21,0],[.97,.10,1.35],'#5a3b34',[0,0,.57]);d('box',[.77,2.21,0],[.97,.10,1.35],'#5a3b34',[0,0,-.57]);d('box',[0,1.85,0],[.75,.3,1.03],'#8b5c3e');d('box',[.73,2.62,-.45],[.19,.58,.2],'#c19170');d('box',[.43,.53,1.06],[.32,.7,.055],'#493831');d('sphere',[.61,.54,1.14],[.044,.044,.02],'#f4ce6f');d('box',[-.64,1.04,1.07],[.36,.36,.035],'#ead9b8');d('box',[-.64,1.04,1.11],[.28,.28,.025],'#ffdf8d',[],.8);d('box',[-.64,1.04,1.14],[.025,.29,.025],'#b17c54');d('box',[-.64,1.04,1.14],[.29,.025,.025],'#b17c54');d('box',[.4,-.03,1.42],[.51,.12,.32],'#c6b796');});
 for(const tree of trees){group([tree.x,-.19,tree.z],[tree.s,tree.s,tree.s],[0,0,0],()=>{d('cylinder',[0,.5,0],[.13,.65,.13],'#765d46');d('cone',[0,1.12,0],[.73,.9,.73],'#386b5e');d('cone',[0,1.8,0],[.57,.78,.57],'#448770');d('cone',[0,2.36,0],[.38,.64,.38],'#5a987e');});}
 for(let i=0;i<11;i++){const x=Math.sin(i*6.2)*5,z=2.8+Math.cos(i*4)*1.8;d('sphere',[x,-.1,z],[.22,.14,.17],'#b6c4ad');}for(let i=0;i<13;i++){const x=-4.4+i*.21,z=1.9+Math.sin(i)*.3;d('sphere',[x,.0,z],[.07,.09,.07],i%2?'#ffdf83':'#e9ad87');}
 if(state.mode==='home'||state.launchTime<2){const walking=state.mode==='launch',progress=walking?Math.min(1,state.launchTime/2):0,walk=progress*progress*(3-2*progress),steps=progress*Math.PI*10,envelope=Math.sin(progress*Math.PI),wobble=walking&&!state.reduced?Math.sin(steps)*.15*envelope:0,bob=walking&&!state.reduced?Math.abs(Math.sin(steps))*.09*envelope:0,boarding=Math.max(0,(progress-.82)/.18);group([-.05+walk*2.65,bob+boarding*.45,1.85*(1-walk)],[.87,.87,.87],[0,walking?1.98:.1,wobble],()=>character(walking?0:t));}group([2.6,.44+launch,0],[.8,.8,.8],[0,0,0],()=>rocket(t,launch>0));if(launch>0)for(let i=0;i<9;i++){const a=i*2.4,r=(launch*.12+i*.07);d('sphere',[2.6+Math.cos(a)*r,.05+(i%3)*.16,Math.sin(a)*r],[.28,.20,.28],'#d7e2d3');}
 // Soft, floating clouds on the horizon.
 for(const [x,y,z]of [[-9,7,-16],[7,8,-17],[1,9,-23]]){d('sphere',[x,y,z],[1.9,.5,.7],'#c4ded6');d('sphere',[x-.4,y+.35,z],[.9,.65,.7],'#d4e6df');}}
function starScene(t,flight=false){for(const s of stars){let x=s.x;if(flight)x=((s.x-state.starTravel+60)%60+60)%60-30;d(flight&&!state.reduced?'box':'sphere',[x,s.y,s.z],flight&&!state.reduced?[s.s*(1+state.speed*5),s.s*.5,s.s*.5]:[s.s,s.s,s.s],s.s>.04?'#dce6f5':'#769aab',[],1);}}
function planet(p,t,pos=[0,0,0],scale=1){
 const tilt=p.id==='uranus'?1.7:p.id==='saturn'?.46:p.id==='earth'?.409:p.id==='mars'?.44:0;
 group(pos,[scale,scale,scale],[.12,0,tilt],()=>{const sz=p.size;
 renderer.draw('globe',[0,0,0],[sz,sz*(p.id==='saturn'?.91:p.id==='jupiter'?.94:1),sz],'#ffffff',[0,t*.025,0],p.id==='sun'?1:0,0,PlanetArt.get(p.id));
 for(const band of PlanetArt.rings(p.id))d('ringlet',[0,0,0],[sz*band.r,1,sz*band.r],band.color,[],.35);
 if(p.id==='sun'&&!state.reduced){for(let i=0;i<9;i++){const a=i*2.4+t*.018,rr=sz*1.025;d('sphere',[Math.cos(a)*rr,Math.sin(a)*rr,0],[.05,.13+.025*Math.sin(t+i),.04],'#ffd575',[0,0,a],1);}}
 });}
function flightScene(t){const pr=Math.min(1,state.elapsed/state.total),p=state.target,boost=Math.max(0,state.speed-1)/2;renderer.begin([0,3,20],[0,.2,0],'#080f24');starScene(t,true);const targetX=11-pr*1.8,targetScale=.3+pr*.60;planet(p,t,[targetX,-.5,-5],targetScale);if(state.origin.id!=='sun'&&pr<.3)planet(state.origin,t,[-13-pr*25,-3,-9],.8);if(state.flyby){const phase=Math.min(1,state.flybyTime/5),x=state.reduced?0:9-phase*22,scale=state.reduced?.48:.24+Math.sin(phase*Math.PI)*.45;planet(state.flyby.body,t,[x,-2.25,1],scale);}
 const bob=state.reduced?0:Math.sin(t*2)*.17;const surge=state.rocketOffset*(state.reduced?.4:1)*(1-pr*.45),requestedRocketX=-3+pr*.8+surge,safeGap=4.2+targetScale*1.8,rocketX=Math.min(requestedRocketX,targetX-safeGap);
 group([rocketX,bob,2],[1.4,1.4,1.4],[0,0,-Math.PI/2+.09-boost*.08],()=>rocket(t,true));
 if(boost>.04&&!state.reduced){for(let i=0;i<16;i++){const x=rocketX-2-((state.starTravel*1.8+i*.87)%12),y=bob+Math.sin(i*6.17)*(1.1+boost*2.4);d('box',[x,y,1-i%3],[.18+boost*.9,.012+boost*.006,.012],i%3?'#79e4e2':'#ffdf70',[],1);}if(state.boostFlash>0){for(let i=0;i<2;i++){const age=(t*2+i*.5)%1,r=.45+age*1.2;d('ring',[rocketX-1.4-age*3,bob,2],[r,1,r],i?'#ffdf70':'#79e4e2',[0,0,Math.PI/2],.7);}}}}
function arrivalScene(t){const a=state.angle,p=state.location,dist=scene.clientWidth/Math.max(1,scene.clientHeight)<.95?20:17;renderer.begin([Math.sin(a)*dist,3,Math.cos(a)*dist],[0,0,0],'#090f27');starScene(t);planet(p,t);const rt=state.reduced?.3:t*.2,rx=Math.cos(rt)*5.7,rz=Math.sin(rt)*5.7;group([rx,.5,rz],[.52,.52,.52],[.1,0,-.24],()=>rocket(t,true));const effectColors={mercury:'#c9c2b7',venus:'#f0ce9e',mars:'#e5a176',jupiter:'#e9b381',saturn:'#e6d8b0',uranus:'#b9f4ee',neptune:'#7bbcec',pluto:'#d8efff'};const color=effectColors[p.id];if(!state.reduced){for(let i=0;i<30;i++){const b=i*2.399+t*(p.id==='neptune'?.65:.13),r=p.size+.5+(i%5)*.32,y=Math.sin(i*2+t*.22)*p.size*.7;d(p.id==='pluto'?'box':'sphere',[Math.cos(b)*r,y,Math.sin(b)*r],[.025+(i%3)*.015,.03,.025],color,[t,i,t],.6);}}
 }
function sunScene(t){renderer.begin([0,3,19],[0,0,0],'#281329');starScene(t);planet(BODIES[0],t,[3,0,-2],1.3);const s=state.sunTime;if(s<2){group([-3+.5*s,0,2],[.8,.8,.8],[0,0,-1.2],()=>rocket(t,true,s>1));}if(s>.7){for(let i=0;i<24;i++){const a=i*2.4,age=Math.min(s-.7,2.5),r=age*(.5+i%5*.23);d('box',[-2.4+Math.cos(a)*r,Math.sin(a)*r,2+Math.sin(i)*r],[.05,.09,.05],i%2?'#ffba43':'#ff7540',[s*i,s,0],1);}}
 if(s>1.6){const x=-3-(s-1.6)*1.9,y=(s-1.6)*.55;d('sphere',[x,y,3],[.55,.49,.48],'#edeadc');d('sphere',[x,y,3.42],[.28,.27,.09],'#7fe0dd');d('sphere',[x,y-.01,3.51],[.15,.16,.035],'#f5cca7');d('cone',[x+.72,y,3],[.18,.5,.18],'#89dfda',[0,0,-Math.PI/2],1);}}
function tick(now){if(!renderer)return;const dt=Math.min((now-lastFrame)/1000,1);lastFrame=now;if(!state.paused){state.clock+=dt;if(state.mode==='launch'){const prev=Math.ceil(3-state.launchTime);state.launchTime+=dt;const n=Math.ceil(3-state.launchTime);if(n!==prev&&n>0)gameAudio.effect('countdown');if(state.launchTime>=2.6&&state.launchTime-dt<2.6)gameAudio.effect('launch');$('countdown').textContent=n>0?String(n):'';$('countdown').hidden=n<=0;if(state.launchTime>=3.7){state.mode='flight';$('countdown').hidden=true;title('UTE PÅ ROMFERD',`Mot ${state.target.name}!`,'Bokstavkraft gir ekstra fart.',state.target.type);scene.setAttribute('aria-label',`Raketten flyr fra ${state.origin.name} til ${state.target.name}.`);}}
 if(state.mode==='flight'){state.elapsed+=dt*state.speed;updateBoost(dt);updateFlybys(dt);state.starTravel+=dt*(2+state.speed*5);updateFlight();if(state.elapsed>=state.total)arrive();}if(wordDelay>0){wordDelay-=dt;if(wordDelay<=0&&['flight','launch'].includes(state.mode))newWord();}if(state.mode==='arrival')state.arrivalTime+=dt;if(state.mode==='sun'){state.sunTime+=dt;if(state.sunTime>1.6&&!state.rescueSound){state.rescueSound=true;gameAudio.effect('rescue');}if(state.sunTime>7){$('sun-flash').classList.remove('active');home(true,true);}}}
 gameAudio.update();const t=state.clock;if(state.mode==='home')homeScene(t);else if(state.mode==='launch'&&state.origin.id==='earth')homeScene(t,Math.pow(Math.max(0,state.launchTime-2.5),2)*6);else if(state.mode==='launch'||state.mode==='flight')flightScene(t);else if(state.mode==='arrival')arrivalScene(t);else if(state.mode==='sun')sunScene(t);renderer.end?.();requestAnimationFrame(tick);}
// Optional browser agent integration uses the exact same actions as touch controls.
if(document.modelContext?.registerTool){for(const tool of [{name:'read_space_adventure',description:'Read current destination, journey progress and spelling prompt.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:state.mode,location:state.location.name,target:state.target?.name,word:state.word,nextLetter:state.word[state.index],speed:state.speed,progress:state.total?state.elapsed/state.total:0})},{name:'start_space_journey',description:'Start a new journey to a solar-system destination from home or after arrival.',inputSchema:{type:'object',properties:{destination:{type:'string',enum:BODIES.map(p=>p.id)}},required:['destination'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const p=BODIES.find(p=>p.id===input.destination);if(!p||!startTrip(p))throw Error('Velg et annet reisemål når du er hjemme eller har kommet frem.');return {destination:p.name,seconds:state.total};}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
updateSettings();updatePassport();requestAnimationFrame(tick);
